### ISSUE TITLE
Compiling with libnorm fails

### ISSUE THREAD

**Issue by pebbe** [zeromq/libzmq#1289]
Running configure with --with-norm=/path/to/norm fails

One issue is in `configure`. It has this line:

```
    LIBZMQ_EXTRA_LDFLAGS="-I${norm_path}/include ${LIBZMQ_EXTRA_LDFLAGS}"
```

This should be:

```
    LIBZMQ_EXTRA_LDFLAGS="-L${norm_path}/lib ${LIBZMQ_EXTRA_LDFLAGS}"
```

After changing this, I still get an error while compiling in subdirectory `perf`

Running configure with --with-norm (without a path) also fails with:

```
  CXXLD  libzmq.la
../libtool: line 6003: cd: yes/lib: No such file or directory
libtool: link: cannot determine absolute directory name of `yes/lib'
```

**Comment by bebopagogo** [comment]
Hi,

After changing the LIBZMQ_EXTRA_LDFLAGS line in configure as you suggest below, I was able to build it using:

./configure —with-norm=<path to NORM source tree>

make

What platform are using?  I built this on a Mac OS X 10.10 box, but I can also try it on Linux if that is what you are using?

best regards,

Brian

**Comment by pebbe** [comment]
I am using Linux. Debian 6, amd64. 
gcc version 4.4.5

**Comment by bebopagogo** [comment]
I was able to build it (with the change to the configure file) on my Linux box which is Ubuntu 14.04 using gcc 4.8.2.

I you can send me some more details on the output when the build fails, I can try to help determine the issue.

The steps I used are:

1) Download the NORM source code tree, unzip/untar in my home directory “/home/user”, and build libnorm.so

cd norm/makefiles

make -f Makefile.linux libnorm.so

3) Clone the current libzmq git repository:

git clone https://github.com/zeromq/libzmq.git

4) Create the configure file and run configure with NORM support:

cd libzmq

sh autogen.sh

./configure —with-norm=/home/user/norm/

5) Build:

make

I apologize if there’s more detail here than you need but I wanted to be complete.

best regards,

Brian

**Comment by pebbe** [comment]
I didn't clone from git. I downloaded from http://zeromq.org/intro:get-the-software

```
$ ls -Rl /my/opt/norm-1.5b4
/my/opt/norm-1.5b4:
totaal 8
drwxr-xr-x 2 peter peter 4096 jan  7 23:08 include
drwxr-xr-x 2 peter peter 4096 jan  7 23:07 lib

/my/opt/norm-1.5b4/include:
totaal 24
-rw-r--r-- 1 peter peter 23318 mrt 16  2014 normApi.h

/my/opt/norm-1.5b4/lib:
totaal 652
lrwxrwxrwx 1 peter peter     16 jan  7 23:07 libnorm.so -> libnorm.so.1.0.0
lrwxrwxrwx 1 peter peter     16 jan  7 23:07 libnorm.so.1 -> libnorm.so.1.0.0
-rwxr-xr-x 1 peter peter 662606 jan  7 23:06 libnorm.so.1.0.0

$ tar vxzf zeromq-4.1.0-rc1.tar.gz
$ cd zeromq-4.1.0
$ emacs configure # edit the line for LIBZMQ_EXTRA_LDFLAGS
$ ./configure --prefix=/my/opt/zeromq-4.1.0 --with-pgm --with-libsodium=/my/opt/libsodium-0.4.3 --with-norm=/my/opt/norm-1.5b4 --with-relaxed
$ make
  [...lines omitted]
  CXX    libzmq_la-raw_decoder.lo
  CXX    libzmq_la-raw_encoder.lo
  CXX    libzmq_la-tipc_address.lo
  CXX    libzmq_la-tipc_listener.lo
  CXX    libzmq_la-tipc_connecter.lo
  CXXLD  libzmq.la
make[2]: Map '/my/src/zeromq-4.1.0/src' wordt verlaten
make[1]: Map '/my/src/zeromq-4.1.0/src' wordt verlaten
Making all in doc
make[1]: Map '/my/src/zeromq-4.1.0/doc' wordt binnengegaan
make[1]: Er is niets te doen voor 'all'.
make[1]: Map '/my/src/zeromq-4.1.0/doc' wordt verlaten
Making all in perf
make[1]: Map '/my/src/zeromq-4.1.0/perf' wordt binnengegaan
  CXX    local_lat.o
  CXXLD  local_lat
/usr/bin/ld: cannot find -lnorm
collect2: ld returned 1 exit status
make[1]: *** [local_lat] Fout 1
make[1]: Map '/my/src/zeromq-4.1.0/perf' wordt verlaten
make: *** [all-recursive] Fout 1
```
Again, this time without specifying the directory for libnorm:
```
$ export LIBRARY_PATH=/my/opt/norm-1.5b4/lib
$ export LD_LIBRARY_PATH=/my/opt/norm-1.5b4/lib
$ export CPATH=/my/opt/norm-1.5b4/include
$ ./configure --prefix=/my/opt/zeromq-4.1.0 --with-pgm --with-libsodium=/my/opt/libsodium-0.4.3 --with-norm --with-relaxed
$ make
  [...lines omitted]
  CXX    libzmq_la-tipc_address.lo
  CXX    libzmq_la-tipc_listener.lo
  CXX    libzmq_la-tipc_connecter.lo
  CXXLD  libzmq.la
../libtool: line 6003: cd: yes/lib: No such file or directory
libtool: link: cannot determine absolute directory name of `yes/lib'
make[2]: *** [libzmq.la] Fout 1
make[2]: Map '/my/src/zeromq-4.1.0/src' wordt verlaten
make[1]: *** [all] Fout 2
make[1]: Map '/my/src/zeromq-4.1.0/src' wordt verlaten
make: *** [all-recursive] Fout 1
```
The only time it works without errors is when I specify the path to libnorm with `--with-norm=/my/opt/norm-1.5b4` AND set the environment variables LIBRARY_PATH, LD_LIBRARY_PATH, and CPATH.

**Comment by bebopagogo** [comment]
I double checked on my machines and I actually had a copy of “libnorm.so” in /usr/local/lib so that’s why it was working on my machines (and why I didn’t catch the issue with the LIBZMQ_EXTRA_LDFLAGS not being properly set since it was finding the NORM library in /usr/local/lib.

I guess I need to review what the proper approach to use here is.  It seems that perhaps the “with-norm” should link the static NORM library into libzmq instead of referencing the libnorm.so?  Then you wouldn’t have to worry about having the shared NORM library installed.   If it references the shared library, then that will need to be installed somewhere like /usr/local/lib or otherwise in your LD_LIBRARY_PATH.  I will look at what “—with-pgm” does a little more carefully and perhaps submit a change to make this simpler and/or more bullet proof.

Meanwhile, I guess the work around extra step here is to install libnorm.so somewhere like /usr/local/lib before building libzmq ...

best regards,

Brian

**Comment by pebbe** [comment]
> Meanwhile, I guess the work around extra step here is to install libnorm.so somewhere like /usr/local/lib before building libzmq ...

That doesn't work. You get this error:
```
../libtool: line 6003: cd: yes/lib: No such file or directory
```

**Comment by bebopagogo** [comment]
Did you still provide the —with-norm=<path to source>  in your configure in this case?  I will try some other things tomorrow

**Comment by pebbe** [comment]
--with-norm without a path

**Comment by bebopagogo** [comment]
You need to provide the path so it can find the “normApi.h” header file …

**Comment by xsyourpal** [comment]
I think the problem is with configure.ac file.  The LIBZMQ_EXTRA_LDFLAGS is providing the path to header files instead of the lib directory.   Making the change to configure.ac file and following the libzmq build instructions listed in the previous comments,   completes the build without errors
>>>> snip >>>>
if test "x$with_norm_ext" != "xno"; then
    AC_DEFINE(ZMQ_HAVE_NORM, 1, [Have NORM protocol extension])

    if test "x$wwith_norm_ext" != "xyes"; then
        norm_path="${with_norm_ext}"
        LIBZMQ_EXTRA_CXXFLAGS="-I${norm_path}/include ${LIBZMQ_EXTRA_CXXFLAGS}"
        LIBZMQ_EXTRA_LDFLAGS="-L${norm_path}/lib ${LIBZMQ_EXTRA_LDFLAGS}"
    fi

    LIBS="-lnorm $LIBS"
fi

<<<< snip <<<<<

**Comment by UsamaMehboob** [comment]
If this issue solved or not? I am willing to work on it

**Comment by bebopagogo** [comment]
I haven't tackled this yet (I know it's been here long).  I'm not well-versed in how issues are assigned either.  However, it's straightforward to fix this configure issue.  I have a number of other enhancements on the NORM/ZMQ binding in progress and had planned to include this fix with a pull request with those updates, but that work is taking longer than I anticipated (or actually, my time to work on that has been more limited than I expected).  Probably the easiest path is to just go ahead and clone libzmq, fix the issue, and submit a pull request.  If you take this on and have any questions, feel free to ask me.

**Comment by UsamaMehboob** [comment]
All build commands are working for me which, otherwise, were failing at @pebbe. I built on ubuntu 15.10. I used openpgm 5.2 (https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/openpgm/libpgm-5.2.122.tar.bz2) libsodium(1.0.6), and libnorm 1.5r6 (http://downloads.pf.itd.nrl.navy.mil/norm/src-norm-1.5r6.tgz).
I built and moved the libsodium.so, libpgm.so, and libnorm.so to /usr/local/lib/. After that ran the following commands and it successfully built the libzmq.la
```
$ ./configure --prefix=/home/user/zeromq-4.1.0 --with-pgm --with-libsodium=/home/user/libsodium-0.4.3 --with-norm --with-relaxed
$ make
``` 
@bebopagogo I want to take this issue to fix it. I have some queries regarding it. Since it successfully built (as mentioned above) by moving files to /ur/local/lib. Do you want me to fix this `LIBZMQ_EXTRA_LDFLAGS` issue? so that libzmq.la can be built without placing libnorm.so in /usr/local/lib. is that right? If there is something else, let me know.
Thanks
