### ISSUE TITLE
Remove of ZMQ_IDENTITY_FD socket option from libzmq 4.1rc and trunk

### ISSUE THREAD

**Issue by rodgert** [zeromq/libzmq#1296]
My reasoning for removing it is as follows -

* It is the only option to zmq_getsockopt() that treats option_value as a value/result parameter, all others treat option_value as strictly a result parameter.

* A brief survey of the Posix getsockopt() API shows a similar lack of using option_value as a value/result parameter.

* The original implementation requires the caller to ensure that the returned buffer is sufficient to hold an fd_t, but fd_t is not part of ZeroMQ's public API. It is conditionally defined by platform and on Windows has two potential definitions.

* I'm not comfortable with this blind faith assignment through a pointer, so I submitted a length check change. Unfortunately this introduces a whole new class of potential usage problems for this option.

* I don't know what the intended use case for the option is, but I infer from the test_id2fd test case, that is to build a map of router identity to fd, perhaps to pass fd to getpeername(2) and build a map of identity to peername. If this is indeed the case, this use case is already handled by calling zmq_msg_get(&part, ZMQ_SRCFD), on the message part containing the identity frame.

**Comment by jemc** [comment]
Looks like the merging of #1297 resolves this.

**Comment by rodgert** [comment]
I reverted the change in both trunk and 4.1 as two separate pull reqs,
trunk had an additional revert in the pull request for a change that
attempts to make this option 'safer'.

**Comment by mli** [comment]
Could you please point me a way to link the FD and the identity in a router? My use case is that I want to a monitor a router socket via socket_monitor (such as when the sender's dead), but it only returns me a FD. So I need to use this FD to find the according sender (e.g. it's identity). ZMQ_IDENTITY_FD solves this problem since I can store the FD once a message from this sender is received.

**Comment by rodgert** [comment]
You get it from the message itself -

zmq_msg_gets (&msg, "Peer-Address")

**Comment by mli** [comment]
thanks Thomas!

But this is not exactly what I want since 
1. The senders may come from the same machine so they share the same ip
2. The ip I get may even be different to the real used one if there are multi-interfaces
3. I cannot get the ip from the monitor socket `s` created by
```
zmq_socket_monitor(router_socket_, "inproc://monitor", ZMQ_EVENT_ALL))
zmq_connect (s, "inproc://monitor"))
```
My goal is to monitor the aliveness of all dealers sockets connected to `router_socket_`. Since I can only get FD from `s`, I need a mapping from FD to the Identity of the connected dealers.

**Comment by rodgert** [comment]
But, the functionality you are commenting against did exactly what zmq_msg_gets (&msg, "Peer-Address") does 'under the hood', in a somewhat broken way.

The FD returned by zmq_getsockopt(s, ZMQ_FD, ...) is not the TCP socket either (for Router/Dealer, how would that even work?), it is the signaling FD used by the ZMQ context thread(s) to let the zmq_poll() know there's data available in the queue for the given socket to the calling application, or that the socket may accept one message to send.

AFAIK you can only get the Source FD and Peer Address from the per-message metadata.

**Comment by mli** [comment]
Thanks for the information, I will check the metadata later.

Previous I got the `sender_fd` by 
```
zmq_getsockopt(router_socket, ZMQ_IDENTITY_FD, sender_identity) 
```
then I can build a map `map(sender_fd, sender_identity)`
