### ISSUE TITLE
Undocumented new behavior of ZMQ_STREAM in version 4.1.0

### ISSUE THREAD

**Issue by dbo-amadis** [zeromq/libzmq#1316]
The "what changed?" description of version 4.1.0 doesn't include the new behavior of ZMQ_STREAM sockets.
Now a ZMQ message with an empty frame is generated each time a raw TCP client connects to or disconnects from the ZMQ_STREAM socket.
Could you also add a brief description for what the reason(s) the behavior of the ZMQ_STREAM socket had to change,

NOTE: I'm not totally against this idea however I had to spend some time on this issue to find out from the unitary test it was a desired modification

This was impacting my previous developments making the backward-compatibility statement untrue

**Comment by metadings** [comment]
I'm with you. I'm just ignoring the "Conntected" message.

**Comment by hintjens** [comment]
This is indeed a breaking change from 4-0. Shall we turn it off by default
and make an option to enable it?

**Comment by dbo-amadis** [comment]
I guess this behavior got introduced for a good reason?
Ideally the original behavior should remain and as you suggested it could be a new zmq_setsockopt() option
Could a new type of socket (like ZMQ_PEER) could also be an alternative?

For your information, the situation I faced was when a Raw TCP Client was trying to connect to the Binary Star based Server, the Client was first sending a Ping Message to inquirer the Server's state, with the new library ZeroMQ the client's call to connect() was generating a NULL message being internally generated within the Gateway which was mistakenly responding back with a Bad Length Error Response. The Client kept trying to connect back and forth between the Primary and Backup Server.
As 'metadings' pointed out, the fix is only a matter of ignoring any 0 byte message (connect and disconnect) and other companies using ZMQ_STREAM might bump into this kind of issue.

**Comment by metadings** [comment]
I'm just ignoring the message, but I would keep the default and introduce a new socket option.

**Comment by hintjens** [comment]
OK, if someone wants to try their hand at making this, please go ahead,
otherwise I'll do it.

**Comment by hintjens** [comment]
I've fixed this. If someone could confirm that they're happy that libzmq master now works as 4.0.x for stream sockets, I'll backport this fix to 4.1 RC.

**Comment by pijyoi** [comment]
Just an observation. The breakage that @dbo-amadis observed is his usage of ZMQ_STREAM as a server. There is actually another ABI change in 4.1.x for ZMQ_STREAM clients caused by #825. 

#825 (disconnect notifications for ZMQ_STREAM clients) 
#832 (connect notifications for ZMQ_STREAM clients and servers)

Mind you, #825 makes ZMQ_STREAM usable for clients. i.e. ZMQ_STREAM in 4.0.x was not so usable for clients. #832 is also generally needed for clients if the protocol is such that they send the first message upon (re-)connect.

**Comment by hintjens** [comment]
Note we fixed this by sending notifications only when ZMQ_STREAM_NOTIFY is
set on a socket.

**Comment by pijyoi** [comment]
I seem to understand from the ZMQ_STREAM_NOTIFY code that it only affects
connect notifications? Disconnect notifications don't seem to be affected
and are always sent.

(No matter to me since I would always want both notifications)

**Comment by hintjens** [comment]
The setting should control both settings...

**Comment by pijyoi** [comment]
Okay, I have tested it out. ZMQ_STREAM_NOTIFY does not affect the disconnect notifications added by #825.

**Comment by pijyoi** [comment]
@hintjens, the current behaviour of ZMQ_STREAM connect/disconnect notifications is as follows:

 notification|   4.0.x   |   4.1.x   |   4.2.0 (master)
----------| ----------  | ----------| --------------
connect | no | yes | sockopt (defaults to no)
disconnect | no | yes | yes

Two things here:
1) ZMQ_STREAM_NOTIFY doesn't control disconnect notifications 
This could be fixed if 4.2.0 is not considered frozen

2) The ABI is broken twice, from 4.0.x to 4.1.x, and from 4.1.x to 4.2.0
Would it make more sense to leave the default in 4.2.0 to "yes", so that the ABI is only broken once?

**Comment by hintjens** [comment]
In any case the current 4.2.0 behavior is inconsistent. I'm not using
stream sockets so don't have an opinion on the best design (notifications
or not). Since 4.1.x is a stable release, 4.2 should try to be compatible
with that.

So you're right: default in 4.2 should be "yes" with the option setting
both connect and disconnect notifications off...
