### ISSUE TITLE
Alignment issue with zmq_msg_t on SPARC CPU

### ISSUE THREAD

**Issue by baryonix** [zeromq/libzmq#1325]
One of the fields of zmq::msg_t is a pointer, which in some environments (in our case, this is a SPARC CPU in 64-bit mode) requires that an instance of the class be aligned to an 8-byte boundary in memory. SPARC is very picky about alignment - you will get a SIGBUS if this is not observed. Many other RISC CPUs behave similarly.

However the zmq_msg_t type which is used as a placeholder to contain a zmq::msg_t instance in the C API, only contains a char array, which will make the compiler apply a less strict alignment requirement. This results in several test cases failing with SIGBUS.

This could be fixed by turning zmq_msg_t into a union, having a pointer as one of its fields, which will force the compiler to apply correct alignment when allocating a zmq_msg_t.

```diff
--- include/zmq.h.orig  Di. Jan 27 14:43:30 2015
+++ include/zmq.h       Di. Jan 27 14:44:29 2015
@@ -199,7 +199,7 @@
 /*  0MQ message definition.                                                   */
 /******************************************************************************/
 
-typedef struct zmq_msg_t {unsigned char _ [32];} zmq_msg_t;
+typedef union zmq_msg_t {unsigned char _ [32]; void *p;} zmq_msg_t;
 
 typedef void (zmq_free_fn) (void *data, void *hint);
 

```

**Comment by rodgert** [comment]
Most architectures, other than recent Intel models, severely penalize unaligned reads even if they don't issue a fault. Also, since messages are potentially shared by threads anyway, they should be aligned to some multiple of the architecture's cache line size (32 bytes for SPARC) to also avoid false sharing. The current version of libzmq defines sizeof(zmq_msg_t) to be 64 bytes for this reason.

Adding __attribute__((aligned(64))) __declspec(align(64)) should be sufficient to meet both of these goals yes?

**Comment by rodgert** [comment]
Scratch my previous comment, there should be no chance of false sharing for a zmq_msg_t if used correctly.
