### ISSUE TITLE
ZMQ Returns EAGAIN without using NOBLOCK during large send()

### ISSUE THREAD

**Issue by meawoppl** [zeromq/libzmq#1332]
When sending messages around the size of 2^29 - 2^31 bytes on send() will return a EAGAIN error state.  Reproduced by @minrk and @belisarius222 in linux/osx/win.  All 64 bit.  

Democode in c: https://gist.github.com/minrk/cd70dce79cf0d8e50fb7

Democode in Python:

``` python
In [11]: import zmq
In [12]: ctx = zmq.context()
In [17]: s = ctx.socket(zmq.PUB)
```

The following runs fine:

``` python
In [18]: s.send_pyobj([1]*(2**29))
```

The following does not:

``` python
In [19]: s.send_pyobj([1]*(2**30))
---------------------------------------------------------------------------
Again                                     Traceback (most recent call last)
<ipython-input-6-9693fcc93b5f> in <module>()
----> 1 s.send_pyobj([1]*(2**30))

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/sugar/socket.py in send_pyobj(self, obj, flags, protocol)
    366         
    367         msg = pickle.dumps(obj, protocol)
--> 368         return self.send(msg, flags)
    369 
    370     def recv_pyobj(self, flags=0):

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/backend/cython/socket.cpython-34m.so in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5434)()

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/backend/cython/socket.cpython-34m.so in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5196)()

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/backend/cython/socket.cpython-34m.so in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2035)()

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/backend/cython/socket.cpython-34m.so in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6112)()

Again: Resource temporarily unavailable
```

I suspect this is due to some form of memory allocation problem, but the doc's do not list this as a possible error state of the send function.  Above demos are with SUB socket type, but original error was exhibited on both sides of a PUSH-PULL pair on the same computer over tcp.  

Original tracking in pyzmq [here](https://github.com/zeromq/pyzmq/issues/642).

**Comment by hintjens** [comment]
It should probably return ENOMEM, right?

**Comment by meawoppl** [comment]
Yeah, that would make a lot more sense IMHO.  I spent a couple hours discovering that we had botched an array size operation (think two extra zeros), but it would have been far more obvious with a hint about memory :)

Do you accept PR's through github?

**Comment by hintjens** [comment]
Yes, PRs is how we work. The contribution policy is here:
http://rfc.zeromq.org/spec:22

**Comment by meawoppl** [comment]
Cool, any leads on where to start looking at?  I stared at this for a bit more than an hour without much headway.  A quick review of all appearances of EAGAIN turned up only one candidate (in the tcp interfaces)  I will test and see if this still occurs with different transport types.

**Comment by hintjens** [comment]
I don't know the code that well. Best would be to ask on zeromq-dev.

**Comment by rodgert** [comment]
I was planning to try and chase this down over the weekend, but as a
starting point - add this as a failing test, fire up gdb, start stepping :)

**Comment by rodgert** [comment]
I also have a low grade suspicion that the problem here is related to 2^31
exceeding implicit limit, maybe overflowing an int size, etc. you may not
be looking for an explicit return of EAGAIN from the libzmq code.

**Comment by meawoppl** [comment]
I am not really a c/c++ dev, but learning to use GDB in a basic way has been on the list for a while now.  
I will see if I can allocate some time this weekend to looking at this a bit more.  My initial problems were as crossing the 2^29 to 2^30 gap, so I still suspect a memory issue getting coerced confusingly.

**Comment by radupopescu** [comment]
Hello,

@meawoppl, I looked a bit at the C code you posted. It seems to me that the message is properly allocated. However, when the message is sent (`zmq_msg_send` which in turn calls `s_sendmsg`) the size is cast to an int (zmq.cpp:335):

```c
static int
s_sendmsg (zmq::socket_base_t *s_, zmq_msg_t *msg_, int flags_)
{
    int sz = (int) zmq_msg_size (msg_);
    int rc = s_->send ((zmq::msg_t*) msg_, flags_);
    if (unlikely (rc < 0))
        return -1;
    return sz;
}
```
This size (negative number due to cast) is returned by `zmq_msg_send`. If I remove the check on the return value of the `zmq_msg_send` function in your example, the program seems to keep sending messages until it runs out of memory on my computer (16 GB).

In any case, a 2GB message seems quite large and unwieldy.

I hope this helps,
Radu

**Comment by meawoppl** [comment]
Great catch @radupopescu.  Looking at it there are a number of casts, the one you reported and:
* https://github.com/zeromq/libzmq/blob/master/src/zmq.cpp#L579
* definition of [zmq_send_msg](https://github.com/zeromq/libzmq/blob/master/src/zmq.cpp#L572)
* definition of [s_sendmessage](https://github.com/zeromq/libzmq/blob/master/src/zmq.cpp#L333)

It seems like the max message size is pretty baked in to the sizeof(int).  
There is an alternative approach where a variable like ZMQ_MAX_MESSAGE_SIZE is exposed which is really just a small calculation based on sizeof(int).   This could also be used to sanity check the send/recv calls.  I can see some terrible situations where sender has a different max size the the receiver.   

I totally get that its an overlarge message size, I originally encountered this bug when a division by ten was missing on image dimensions (think >100x normal message size).  It is not a real use-case for me to be sending 2**32 byte messages.  

Does that suggest that the EAGAIN was just the last error state (probably from an earlier poll() or some such), and is completely unrelated?

**Comment by radupopescu** [comment]
Hello @meawoppl,

Ok, I understand your usage scenario and how you came across this bug.

Yes, it seems that the message size is assumed to be an `int`. Well `size_t` is used, before it is cast down to an `int`. I am wondering if this is not done on purpose, since in the C++ standard `size_t` is implementation defined and is different on 32bit and 64bit machines, which is not the case for `int`. With `size_t`, you could have issues with message sizes when a 32bit machine is trying to talk to a 64bit one.
 I'd say that it would be more consistent to enforce the `int` message size everywhere (also fail when trying to allocate a message that is larger that this), but there could be reasons for the current choice. Maybe one of the ZMQ developers could clarify this.

Regarding the value of EAGAIN, I think this is the case, it comes from some earlier operation. Just try printing the error string before and after the message send, at each iteration.

Best regards,
Radu

**Comment by meawoppl** [comment]
I came back to this from a stack overflow question here:
http://stackoverflow.com/questions/6543123/zeromq-message-size-length-limit/35007517#35007517

I realize that it isn't really pressing to fix this, but I think its worth a mention in the docs somewhere that messages of this size don't really fit the design paradigm.
