### ISSUE TITLE
ZMQ_FD doesn't work with inproc sockets

### ISSUE THREAD

**Issue by jkarneges** [zeromq/libzmq#1434]
The fd never triggers a read notification. Works fine with ipc/tcp socket types. Is this a known issue?

Tested with 4.1.1.

**Comment by hintjens** [comment]
Sounds right. Probably worth documenting.

**Comment by jkarneges** [comment]
Any tips on how to address this in the code? This issue prevents inproc being used reliably in event-driven/coroutine environments. I suppose I could just not use zmq for in process communication, but the spirit of zmq is that it should work in all scopes.

**Comment by hintjens** [comment]
Can you not find another way to trigger events?

**Comment by jkarneges** [comment]
How do you mean? A receiving socket's ZMQ_FD doesn't trigger if the peer socket sends to it. What else is there to do?

**Comment by hintjens** [comment]
I'm not familiar with the approach you're using; all my code uses polling
on sockets, and does not depend on triggering FDs.

**Comment by jkarneges** [comment]
Ah yes, if you don't need to integrate with an existing polling/evented system then you can just use zmq_poll. In my case, I'm using libraries like Qt and lthread that already contain their own poll loop. It's not practical to convert these systems to use zmq_poll.

**Comment by MishkaRogachev** [comment]
Hove same problem. I use QSocketNotifier from Qt, and it forks fine with subscriber on tcp, but not with inproc. But if disturb it by recv(ZMQ_NOBLOCK), it may throw some messages

**Comment by eile** [comment]
We've got the same issue -- needing to use an inproc socket to communication between two OS threads in combination with QSocketNotifier (which uses select), i.e., the native handle can't be polled for read data.

**Comment by garlick** [comment]
We have successfully integrated zmq with libev following the strategy outlined [here](https://funcptr.net/2013/04/20/embedding-zeromq-in-the-libev-event-loop/).  We use this heavily with `inproc://` so when this issue was created a year ago I opened a bug in our project to investigate.  Since we had not observed any problem, it languished.

Finally getting back to it, we can reproduce this perhaps unexpected behavior:
(the `ok()` calls are part of our TAP test harness - they just print "ok" or "not ok" depending on whether the expression in the first argument evalutes true or false.)
```C
    void *zctx;
    void *zin, *zout;
    int fd;

    ok ((zctx = zmq_init (1)) != NULL,
        "initialized zmq context");
    ok ((zout = zmq_socket (zctx, ZMQ_PAIR)) != NULL
        && zmq_bind (zout, "inproc://eventloop_test") == 0,
        "PAIR socket bind ok");
    ok ((zin = zmq_socket (zctx, ZMQ_PAIR)) != NULL
        && zmq_connect (zin, "inproc://eventloop_test") == 0,
        "PAIR socket connect ok");
    size_t fd_size = sizeof (fd);
    ok (zmq_getsockopt (zin, ZMQ_FD, &fd, &fd_size) == 0 && fd >= 0,
        "zmq_getsockopt ZMQ_FD returned valid file descriptor");
    ok (zstr_send (zout, "TEST") == 0,
        "sent a message over PAIR sockets");
    struct pollfd pfd = { .fd = fd, .events = POLLIN };
    ok (poll (&pfd, 1, 1000) == 1,
        "poll says edge triggered mailbox descriptor is ready");
    uint32_t zevents;
    size_t zevents_size = sizeof (zevents);
    ok (zmq_getsockopt (zin, ZMQ_EVENTS, &zevents, &zevents_size) == 0
        && (zevents & ZMQ_POLLIN),
        "zmq_getsockopt ZMQ_EVENTS says PAIR socket ready to recv");
```
The `poll()`  times out after 1000ms and the test fails.  Apparently there is no "edge" making the ZMQ_FD ready, despite my `zstr_send()`.

However, if I insert a request for ZMQ_EVENTS _before_ the `zstr_send()`, it works.
```C
    ok ((zctx = zmq_init (1)) != NULL,
        "initialized zmq context");
    ok ((zout = zmq_socket (zctx, ZMQ_PAIR)) != NULL
        && zmq_bind (zout, "inproc://eventloop_test") == 0,
        "PAIR socket bind ok");
    ok ((zin = zmq_socket (zctx, ZMQ_PAIR)) != NULL
        && zmq_connect (zin, "inproc://eventloop_test") == 0,
        "PAIR socket connect ok");
    size_t fd_size = sizeof (fd);
    ok (zmq_getsockopt (zin, ZMQ_FD, &fd, &fd_size) == 0 && fd >= 0,
        "zmq_getsockopt ZMQ_FD returned valid file descriptor");
+   uint32_t zevents;
+   size_t zevents_size = sizeof (zevents);
+   ok (zmq_getsockopt (zin, ZMQ_EVENTS, &zevents, &zevents_size) == 0
+      && !(zevents & ZMQ_POLLIN),
+      "zmq_getsockopt ZMQ_EVENTS says PAIR socket not ready to recv");
    ok (zstr_send (zout, "TEST") == 0,
        "sent a message over PAIR sockets");
    struct pollfd pfd = { .fd = fd, .events = POLLIN };
    ok (poll (&pfd, 1, 1000) == 1,
        "poll says edge triggered mailbox descriptor is ready");
    ok (zmq_getsockopt (zin, ZMQ_EVENTS, &zevents, &zevents_size) == 0
        && (zevents & ZMQ_POLLIN),
        "zmq_getsockopt ZMQ_EVENTS says PAIR socket ready to recv");
```
It turns out our libev "zmq watcher" always tests ZMQ_EVENTS and ensures no events are pending before before allowing libev to poll (block) on the ZMQ_FD, so we don't hit this.

I'm curious if this particular quirk explains the behavior reported by others or if something else is wrong?

**Comment by somdoron** [comment]
You solution is correct and exactly how zmq_poll and zmq_poller works. ZMQ_FD is edge triggered, zmq_poll turns it into level triggered

**Comment by jkarneges** [comment]
@somdoron the above code is not a solution but it helps show that there is a problem. It checks events on the peer socket before sending. That works in a unit test that owns both ends of a socket, but is complete nonsense in a real app. :)

**Comment by somdoron** [comment]
Does the problem still exist if you do the following:
When a FD is signalled read all messages in the queue, until you get eagain (use DONT_WAIT flag).  You can now poll on the FD again and it should be signalled again.

**Comment by somdoron** [comment]
You might need to try and recv before the first poll. The way the internal siganling works is like this: queue message, if reader is asleep send him a command to wake up. Command is what singalling the FD, but not always, only when the command queue is empty. Your problem is that the command queue is not empty so the calling send or poll doesnt signal the FD. To solve you must empty the command queue. ZMQ_EVENTS, recv and send process all commands. Bottom line, before a call to poll process all pending messages until EAGAIN.

Sent from mobile, so excuse my typos

**Comment by garlick** [comment]
I think @somdoron's explanation agrees with the assumptions in our "ev_zmq watcher" for libev integration, which is here:

https://github.com/flux-framework/flux-core/blob/master/src/common/libutil/ev_zmq.c
https://github.com/flux-framework/flux-core/blob/master/src/common/libutil/ev_zmq.h

I am fairly confident it is working as designed and not suffering from the sort of problem this issue might suggest, like unexplained pauses where messages have to wait for an event other than the ZMQ_FD to wake up the event loop.

**Comment by Jajauma** [comment]
So the issue ain't gonna get fixed, am I right?

**Comment by somdoron** [comment]
You are correct,  but there is no really issue here,  or the issue is with the documentation. When using zeromq socket with external polling library the FD is edge triggered. So you must fetch all messages before polling again

**Comment by Jajauma** [comment]
Indeed, if I force draining the receiving side before passing to QSocketNotifier e.g.
```
        // https://github.com/zeromq/libzmq/issues/1434
        ZeroMQMessage dummy;
        while (ZeroMQSafe::zmq_msg_recv(
            dummy.Raw(), mInputEndpoint->Raw(), ZMQ_DONTWAIT))
            ;

        mSocketNotifier = new QSocketNotifier(
            GetFD(mInputEndpoint), QSocketNotifier::Read, this);
```
the things seem to just work. Pretty much awkward but if you say it is an expected behaviour I guess it's quite another matter then.

**Comment by bluca** [comment]
This is a good writeup on edge vs level trigger:

https://funcptr.net/2012/09/10/zeromq---edge-triggered-notification/

**Comment by jkarneges** [comment]
I'll try to confirm this soon. I'm well aware the FD is edge triggered, and my code does check the events flags after each read or write, rather than relying on the FD only. This has been enough for TCP and IPC socket types to work for me, but not inproc.

If the FD is truly supposed to work with inproc as well, then I must be missing an events check or I/O somewhere. I'll double check everything and report back.

**Comment by greggwon** [comment]
The problem with zeromq poll, is that you can't reliably "read all the messages" before "poll", and then poll for an edge triggered event, without some kind of atomic bridge between the two steps.  Why is it that we can't have the returned FD just be "the fd", so that poll(2) just works?   This is an extremely poor choice of implementation and completely violates the "unix" standard for how poll(2) should work, and can be used.   Across the board, zmq seems to miss out on the fact that "unix" has a standard set of tools which all work together and promote trivial integration of multiple event source through the simplicity of poll(2).

**Comment by garlick** [comment]
I think the idea is that you can _either_ use zmq_poll() directly on zeromq sockets and get level-triggered semantics on messages as per usual, _or_ you can use poll(2) on the ZMQ_FD in combination with ZMQ_EVENTS.

ZMQ_FD / ZMQ_EVENTS works reliably with poll(2) if used correctly, though it is tricky.  See above.

ZMQ_FD can't be "the fd" because a zeromq socket can have multiple fd's (to support connections to multiple endpoints), and the zeromq service thread owns those fd's and is already responding to their events.

**Comment by themightyoarfish** [comment]
So I assume this has never been addressed? Is it impossible to implement or has simply no one dedicated time to fixing this problem?

**Comment by garlick** [comment]
My understanding is that  zeromq is working as designed here, although the design is a bit...subtle.  We have code that has been in daily use for years now, built with multiple versions of zeromq, that depends on this behavior and exhibits no problems.
