### ISSUE TITLE
Segfault in 4.1.1 on 32bit when calling socket.recv() from python

### ISSUE THREAD

**Issue by totycro** [zeromq/libzmq#1436]
Hi,

I just updated from 4.0.5 to 4.1.1 on my UCS 32-bit machine (that's debian-based) and now I get a reproducible segfault on every call to socket.recv(). This does not happen on 64 bit and did not happen in 4.0.5. It does not occur in smaller examples so I can only show you what I did:

strace output:
https://bpaste.net/show/22e079463b08

The code for it is located here:
https://github.com/initat-Informationstechnologie-GmbH/icsw/blob/master/initat/tools/threading_tools.py#L1364
https://github.com/initat-Informationstechnologie-GmbH/icsw/blob/master/initat/logging_server/server.py#L580

```
  /opt/python-init/lib/python2.7/bdb.py(400)run()
-> exec cmd in globals, locals
  <string>(1)<module>()
  /opt/python-init/lib/python/site-packages/initat/tools/daemonize.py(117)<module>()
-> main()
  /opt/python-init/lib/python/site-packages/initat/tools/daemonize.py(113)main()
-> main_module.main()
  /opt/python-init/lib/python/site-packages/initat/logging_server/main.py(76)main()
-> main_process(options).loop()
  /opt/python-init/lib/python/site-packages/initat/tools/threading_tools.py(1364)loop()
-> self._poll()
  /opt/python-init/lib/python/site-packages/initat/tools/threading_tools.py(1400)_poll()
-> self._handle_select_list(_socks)
  /opt/python-init/lib/python/site-packages/initat/tools/threading_tools.py(402)_handle_select_list()
-> self.poller_handler[sock][r_type](self._socket_lut.get(sock, sock))
> /opt/python-init/lib/python/site-packages/initat/logging_server/server.py(580)_recv_data()
-> in_str = zmq_socket.recv()
```

regards,
totycro

**Comment by minrk** [comment]
Did you recompile pyzmq after updating libzmq? You probably need to do that.

**Comment by totycro** [comment]
Ah, this seems to have solved it. Thank you & sorry for the report!

**Comment by minrk** [comment]
@hintjens forgive me if this is completely wrong, I've never had a solid grip on C linking, but does this mean that 4.1 is not ABI compatible with 4.0? If so, have the appropriate indicators been updated? I thought that upgrading a library under programs linked to it should either:

1. continue to work
2. fail to load, since libzmq.so.4 is gone, and replaced with libzmq.so.5, etc.

**Comment by xaqq** [comment]
I *think* that we are not promising binary compatibility between release. What is guaranteed is source compatibility only (and network protocol).

It's totally possible for a program to load against a non-binary compatible version of the library it linked against. This can result is random behavior and crash. AFAIK there is no guarantee that it will either work or won't load.

Because we are exporting a C API it should be relatively easy to maintain binary compatibility. I believe the source of the problem between 4.0 and 4.1 is that we changed the size of `zmq_msg_t` from 32bytes to 64bytes.

**Comment by minrk** [comment]
> It's totally possible for a program to load against a non-binary compatible version of the library it linked against. This can result is random behavior and crash. 

But if it changed, the ABI version should have changed as well, right? Is the ABI version for 4.1 different from 4.0?

**Comment by hintjens** [comment]
@minrk you're right IMO, the ABI should have been bumped. I'm a little surprised that didn't crop up during the long RC phase nor on libzmq master. Also the ABI versioning is iffy, e.g. RHEL only looks at the first digit, so you can't use the others in any way. So, we'd have to use 5.0.0. And then people always expect this to match the API version. It is all a mess... :)

If you think it's worth fixing this in 4.1 then I'm happy to make a maintenance release.

**Comment by minrk** [comment]
This happens to pyzmq users with some frequency - upgrade libzmq, don't rebuild pyzmq, segfault. I think failure to load that comes with ABI > changed library path is slightly more informative, so bumping the ABI in 4.1 would probably be helpful. It's not a major issue, though.

**Comment by hintjens** [comment]
Can we check that updating the ABI version in 4.1.x prevents the crash?

Then we can do this and make a new release sooner rather than later...

**Comment by minrk** [comment]
Yup, I'll whip up a test.

**Comment by minrk** [comment]
Bumping the ABI in 4.1 does indeed fix the problem. If 4.0 is still present, it will be used. If 4.0 is removed in favor of 4.1, it will die failing to load libzmq.4 since 4.1 provides libzmq.5.

**Comment by hintjens** [comment]
OK, sounds good. I'll make the change on 4-1 and libzmq master.

Thanks a lot!

**Comment by hintjens** [comment]
OK, done on 4-1 and libzmq master:

https://github.com/zeromq/zeromq4-1/pull/39

**Comment by minrk** [comment]
Awesome, thanks @hintjens!
