### ISSUE TITLE
make check error: tests/test_shutdown_stress

### ISSUE THREAD

**Issue by ppLorins** [zeromq/libzmq#1509]
![image](https://cloud.githubusercontent.com/assets/5534049/9080534/109a0394-3b87-11e5-8f40-64f7f9210aa2.png)

I try to compile libzmq on my mac: Yosemite 10.10.3

After successfully running ./autogen.sh and ./configure , I got the above error while doing make check ,is it curcial for compling libzmq ? I supposed not , but how does it happen and how to fix  ?   I know it it testing for shutdown not to incur a sigpipe which will cause program core, and afraid of getting some issues at run time if I get round the error.

**Comment by bluca** [comment]
Hi,

I think I remember facing a similar problem when working on the CI, and if I remember correctly I was able to get past it with the following commands to increase the per-process file limit (OSX default was too low):

sudo sysctl -w kern.maxfiles=64000
sudo sysctl -w kern.maxfilesperproc=64000
sudo launchctl limit maxfiles 64000 64000
ulimit -n 64000

**Comment by jgornowich** [comment]
I just pulled down the lastest as of December 1 and am seeing the same test fail that this issue was generated for.  I have seen the same problem today on two different systems, Centos 7.1 and Linux Mint 17.1, here is the partial output of the test suite:

...
PASS: tests/test_many_sockets
PASS: tests/test_ipc_wildcard
PASS: tests/test_diffserv
PASS: tests/test_connect_rid
PASS: tests/test_bind_src_address
PASS: tests/test_metadata
PASS: tests/test_capabilities
PASS: tests/test_xpub_nodrop
PASS: tests/test_xpub_manual
PASS: tests/test_xpub_welcome_msg
PASS: tests/test_atomics
PASS: tests/test_client_server
PASS: tests/test_thread_safe
PASS: tests/test_socketopt_hwm
PASS: tests/test_heartbeats
PASS: tests/test_stream_exceeds_buffer
PASS: tests/test_poller
./config/test-driver: line 107: 25594 Segmentation fault      "$@" > $log_file 2>&1
FAIL: tests/test_shutdown_stress
PASS: tests/test_pair_ipc
PASS: tests/test_reqrep_ipc
PASS: tests/test_timeo
PASS: tests/test_filter_ipc
PASS: tests/test_fork
PASS: tests/test_abstract_ipc
...

I decided to run the test by hand out of the test directory and got several different results:

- Assertion failed: !sink (src/pipe.cpp:112)
- Bad address (src/pipe.cpp:368)
- Assertion failed: state == active || state == delimiter_received || state == term_req_sent1 (src/pipe.cpp:304)
- Assertion failed: false (src/object.cpp:400)

Sometimes it does not even show an assertion statement and just seg faults.  I did not dig much further.

**Comment by jakirkham** [comment]
Also seeing this issue on Mac OS 10.9.

**Comment by jakirkham** [comment]
Related ( https://github.com/zeromq/libzmq/issues/1878 ).

**Comment by ilovezfs** [comment]
I can avoid this failure with the following:
```
diff --git a/src/stream_engine.cpp b/src/stream_engine.cpp
index 2e57ec3..0576e13 100644
--- a/src/stream_engine.cpp
+++ b/src/stream_engine.cpp
@@ -137,7 +137,7 @@ zmq::stream_engine_t::stream_engine_t (fd_t fd_, const options_t &options_,
     //  connection that was already closed by the peer.
     int set = 1;
     rc = setsockopt (s, SOL_SOCKET, SO_NOSIGPIPE, &set, sizeof (int));
-    errno_assert (rc == 0);
+    // errno_assert (rc == 0);
 #endif
     if(options.heartbeat_interval > 0) {
         heartbeat_timeout = options.heartbeat_timeout;
diff --git a/src/tcp.cpp b/src/tcp.cpp
index a6de129..0d6e861 100644
--- a/src/tcp.cpp
+++ b/src/tcp.cpp
@@ -56,7 +56,7 @@ void zmq::tune_tcp_socket (fd_t s_)
 #ifdef ZMQ_HAVE_WINDOWS
     wsa_assert (rc != SOCKET_ERROR);
 #else
-    errno_assert (rc == 0);
+    // errno_assert (rc == 0);
 #endif
 
 #ifdef ZMQ_HAVE_OPENVMS

```

First I was getting Invalid argument (src/stream_engine.cpp:140), and then later the same for tcp.cpp once the stream_engine.cpp one was commented out.

The kernel is kicking in with entries in the system log like`kernel[0] <Notice>: Limiting closed port RST response from 423 to 250 packets per second`.

It looks like this may avoidable using sysctls (net.inet.tcp.blackhole and net.inet.udp.blackhole), but those errno's should not be expected to always be zero under stress.

See https://discussions.apple.com/thread/842719 for some discussion.

**Comment by bluca** [comment]
I'll read that discussion, but in general I'm not a huge fan of just disabling asserts when things fail

**Comment by ilovezfs** [comment]
@bluca I am not suggesting you disable the asserts. But your current test will reliably trigger them, and it's the OS deliberately protecting against potentially malicious behavior.

**Comment by bluca** [comment]
Yep should absolutely be looked into, I'll read the link today or tomorrow, thanks for the pointer!

**Comment by ilovezfs** [comment]
Also,
https://major.io/2007/06/06/freebsd-limiting-closed-port-rst-response/
