### ISSUE TITLE
ZeroMQ will crash under Windows if port 5905 is in use by another process

### ISSUE THREAD

**Issue by mattbolgercsiro** [zeromq/libzmq#1542]
The use of port 5906 as the event_signaler_port is hard coded in two locations (signaler.cpp and config.hpp). If this port is already in use (in my case by RealVNC) then ZeroMQ will crash on the first call to WinSock select().

Shouldn't this port being in use be handled more gracefully and be caught at the actual setup of the sockets in signaler_t::make_fdpair()? 

http://lists.zeromq.org/pipermail/zeromq-dev/2015-August/029451.html

**Comment by pijyoi** [comment]
The original implementation of a Windows signaler socket used port 5905 instead of letting the OS choose a free port. This also required a global mutex to be locked to prevent simultaneously running zeromq programs from clashing. 

Unfortunately the mutex was implemented with an Event instead of a Mutex. Changing it to a Mutex would break compatibility with existing programs unless the port was also changed. 

The hardcoded value of 5905 in signaler.cpp is just to check what port was configured in config.hpp. If 5905 it uses back the old Event implementation else it uses a Mutex. 

If 0, it lets the OS choose a free port without requiring use of a global mutex. (This is the best solution imho)

You could submit a PR to change the default value in config.hpp to 0.

**Comment by hitstergtd** [comment]
Close issue as PR was accepted and merged.

**Comment by bluca** [comment]
This was fixed a good while ago, which version are you using?
