### ISSUE TITLE
No check for singaler::get_fd () for '-1'

### ISSUE THREAD

**Issue by Thovart** [zeromq/libzmq#1558]
Initially,
_reaper_ contains _mailbox_t_ which contains _signaler_ 
zmq::signaler_t::make_fdpair initializes its internal structures. **But if it fails to initialize 'r' member, it still is a valid object! No exceptions are thrown** So, _reaper_ calls
``` c++
mailbox_handle = poller->add_fd (mailbox.get_fd (), this);
```
with already invalid FD (== -1)
which causes crash in the zmq::poll_t::add_fd

``` c++
zmq::poll_t::handle_t zmq::poll_t::add_fd (fd_t fd_, i_poll_events *events_)
{
    //  If the file descriptor table is too small expand it.
    fd_table_t::size_type sz = fd_table.size ();
    if (sz <= (fd_table_t::size_type) fd_) {
        fd_table.resize (fd_ + 1);
        while (sz != (fd_table_t::size_type) (fd_ + 1)) {
            fd_table [sz].index = retired_fd;
            ++sz;
        }
    }
```

```
0d4ef4b0 09c4a6f9 zmq_infra!zmq::poll_t::add_fd(unsigned int fd_ = 0xffffffff, struct zmq::i_poll_events * events_ = 0x0b6229ac)+0x72 [k:\1309\third-party\zeromq\src\poll.cpp @ 60]
0d4ef4e0 09c3fa13 zmq_infra!zmq::reaper_t::reaper_t(class zmq::ctx_t * ctx_ = 0x07196a68, unsigned int tid_ = 0xb64f978)+0xd9 [k:\1309\third-party\zeromq\src\reaper.cpp @ 33]
0d4ef51c 09c3da31 zmq_infra!zmq::ctx_t::create_socket(int type_ = 0n5)+0xe3 [k:\1309\third-party\zeromq\src\ctx.cpp @ 252]
0d4ef52c 09c326dd zmq_infra!zmq_socket(void * ctx_ = 0x07196a68, int type_ = 0n5)+0x21 [k:\1309\third-party\zeromq\src\zmq.cpp @ 254]
0d4ef550 09c33463 zmq_infra!zmq::socket_t::socket_t(class zmq::context_t * context_ = 0x07246998, int type_ = 0n5)+0x1d [k:\1309\third-party\cppzmq\zmq.hpp @ 317]
```

**Comment by c-rack** [comment]
Just took a short look. I understand that the problem is that `make_fd` could return `-1` in some situations and we just ignore this case in the signaler constructor and leaving fds uninitialized:
https://github.com/zeromq/libzmq/blob/master/src/signaler.cpp#L126-L130

So, the solution is to just check the return code of `make_fd()` call in `signaler`'s constructor with `zmq_assert()`, correct?

If there are no objections, I would send a PR.

**Comment by c-rack** [comment]
@Thovart Please check if current master branch solves your problem, thanks!

**Comment by c-rack** [comment]
So I had to revert my first solution because it broke the build and was not the proper solution to the problem described in this issue.

Let me describe what happens and how the correct solution should look like:

Generally, we are dealing here with a "too many open files" situation. If this happens, the `make_fdpair`  sets the file descriptors `r` and `w` to `-1`. And that is ok.

During construction of a new socket, we create a new `reaper_t` which in turn creates a new `poller_t` and calls `add_fd` on the poller. In our "too many open files" situation, `add_fd` is called with `-1`. The type of `poller_t` depends on the system, it can be `poll_t`, `kqueue_t`, `epoll_t`, etc.

It seems that all poller implementations are immune to a `add_fd(-1,...)` call except `poll_t` and `devpoll_t`. They fail silently but do not crash. Later, the check if the mailbox file descriptor is `-1` is then performed by `zmq::socket_base_t::create` and results in `zmq_socket()` to return `NULL`, a situation that the caller has to deal with.

So the correct solution would be not to call `add_fd` with invalid fd and to change:
```cpp
    mailbox_handle = poller->add_fd (mailbox.get_fd (), this);
    poller->set_pollin (mailbox_handle);
```
to
```cpp
    if (mailbox.get_fd () != retired_fd) {
      mailbox_handle = poller->add_fd (mailbox.get_fd (), this);
      poller->set_pollin (mailbox_handle);
    }
```
here: https://github.com/zeromq/libzmq/blob/master/src/reaper.cpp#L43-L44
