### ISSUE TITLE
Internal assertion in zeromq\src\signaler.cpp:303

### ISSUE THREAD

**Issue by vit1251** [zeromq/libzmq#1573]
Hello,

Can you explain problem on windows platform over Python binding

Assertion failed: nbytes == sizeof (dummy) (bundled\zeromq\src\signaler.cpp:303)

Whats wrong? Using threads and SUB=>PUB, PUB=>SUB models.

**Comment by bcxc** [comment]
I am also having this problem, when I run python code in pycharm, I think the python.exe file has crashed, maybe for part of my code. and I am using multiThread to read from socket, it I wait for a long time, like 20 second, then it has lower possibility to have this problem.

**Comment by ymax** [comment]
it's possible that the problem is the same as at ubuntu #1583 (socket is changed to non-blocking, but recv() doesn't process this case)

**Comment by cigarhuang** [comment]
I also encounter the same issue.
I build pyzmq from github, and the problem is gone.
My system, windows 7 x64, python 3.3.4 x86, 14.7.0 pyzmq, 4.2.0 libzmq

**Comment by krgn** [comment]
I am also encountering this issue in my Appveyor builds.

My version is 4.1.5 vs 2013 (manually built) in an what appears to be x64 windows environment.

**Comment by somdoron** [comment]
Any chance you are using socket from multiple threads?

**Comment by krgn** [comment]
I'll check that, good point!

**Comment by krgn** [comment]
That was the problem, thanks. It was quite a subtle bug in how the server socket got disposed of (inside one of F#'s Async actions, not the thread that spawned it).

**Comment by joshusre** [comment]
It happened to me.  I use zeromq to talk between a python layer using a dll in ctypes and a websocket server in tornado

**Comment by bluca** [comment]
@joshusre any chance you are using a socket from multiple threads?

**Comment by joshusre** [comment]
I have zmq set in pair mode with my dll and websocket server.  Both are subclasses of the same zmq abstract base.  They transmit tcp to each other via a producer consumer model using python's thread safe queue.

**Comment by bluca** [comment]
What do you mean by "they transmit tcp" ?

**Comment by ymax** [comment]
@joshusre describe the threads that use the sockets.
As we had similar problems very long ago (in 2015 ;), I can tell that the problem was because of using (polling + sending) the same socket in several threads simultaneously (we wanted many worker threads). Yes, there was a lock, but it didn't help. So we ended up by code refactoring to bind a socket to each thread and never since had any problems.

**Comment by flawd95** [comment]
Do we know if this issue is being looked into?  I currently have a problem with this in a project that uses libzmq.

**Comment by bluca** [comment]
Are you using a socket from multiple threads?

**Comment by haf** [comment]
This reproduces the crash pretty well:

```

let recv (conf: TCPConfig) (next: Ingest) =
  // https://gist.github.com/lancecarlson/fb0cfd0354005098d579
  // https://gist.github.com/claws/7231548#file-czmq-stream-server-c-L21
  job {
    try
      while not (Promise.Now.isFulfilled conf.cancelled) do
        let! frame = Job.Scheduler.isolate (fun () -> Socket.recv conf.receiver)
        // Aborted socket due to closing process:
        if isNull frame then () else
        let! bs = Job.Scheduler.isolate (fun () -> Socket.recv conf.receiver)
        // http://api.zeromq.org/4-1:zmq-socket#toc19
        // A connection was made
        if bs.Length = 0 then () else
        // printfn "Data received: %A" message
        use ms = new MemoryStream(bs)
        use sr = new StreamReader(ms, Encoding.UTF8)
        while not sr.EndOfStream do
          let line = Ingested.ofString (sr.ReadLine())
          let! res = next line
          ignore res
        ilogger.verbose (eventX "Looping...")
    with :? ZMQError as zmq ->
      ilogger.info (eventX "Shutting down streamRecvLoop due to {exn}." >> setField "exn" zmq.Message)
  }
```

Crashes directly.

However, there's only one concurrent access to the socket, even though any thread of the thread pool can perform the access.

**Comment by bluca** [comment]
As the documentation says, you cannot use sockets from multiple threads

**Comment by haf** [comment]
@bluca Well, I'm not. Not at the same time. Does ZMQ keep track of thread ids?

**Comment by bluca** [comment]
The documentation doesn't say sockets cannot be used from multiple threads as long as it's not at the same time - it says sockets cannot be used from multiple threads, period

**Comment by haf** [comment]
Does ZMQ keep track of thread ids?

**Comment by vit1251** [comment]
Let's I little clear my 3 years ago question ;)
Python have thread steal mechanism when you start more than one Python thread.
Python create OS thread pool and thread select idle Python thread and do it.
When Python lock on operation Python thread may switch to another Python thread and switch again and again.
I think that Python should implement some bind mechanism for thread like it in golang describe here https://github.com/golang/go/wiki/LockOSThread
Any case implementator of extension for Python should queued request to library with buffered pthread only for operating with libzmq or create another mechanism (if you know one please provide it in comment).

**Comment by bluca** [comment]
It doesn't "know" what's in another thread, data structures used in communications between the application thread and the I/O thread are not thread safe by design, hence the warning in the documentation

If you want thread-safe sockets, build with DRAFT (with all that entails, including API breakages with no warning) and use the new thread-safe socket types

**Comment by haf** [comment]
@bluca Thanks for your continuous support/interaction trying to help us understand. Much appreciated.

> not thread safe

I understand threads fairly well and when this phrase is used it's normally used about data structures that are mutated, e.g. this is not thread safe in any way of the phrase:

```fsharp
let d = Dictionary<string, string>()
let runInPar (key: string) = job { d.[key] <- "world" }
run (Job.conIgnore [ runInPar "a"; runInPar "b" ])
```

But this is safe, even though dictionary is *not thread safe*:

```fsharp
let ops = Ch ()
let rec runInPar () =
  let d = Dictionary<string, string>()
  ops ^=> fun (key: string) ->
    job { d.[key] <- "world"
          return! runInPar () }
run (Job.conIgnore [ ops *<= "a"; ops *<= b" ])
```

The latter will cause the access to the dictionar `d` to jump all over the thread pool, because the callback when the ops channel has a value will run anywhere available.

If a ZMQ thread does not *know* what thread called it, and is only accessed from a single thread at a time, it should be like the dictionary `d`.

**Comment by bluca** [comment]
The data structure used is a lockfree single-writer single-reader queue, you can find the implementation in the repository if you want to know all the details, but what's important for the users is only that each socket _must_ be used from a single thread only
