### ISSUE TITLE
Poll is dangerously wrong for xpub_nodrop sockets

### ISSUE THREAD

**Issue by memeplex** [zeromq/libzmq#1597]
Why is it wrong? Because has_out always returns true for xpub (it just delegates to dist.has_out which is constantly true); nevertheless, a xpub_nodrop pub socket could still block. Why is it dangerous? Because this could easily lead to deadlocks; take for example a forwarder proxy that blindly assumes it could send to the xpub_nodrop xpub in its back; now, a thread subscribed to this xpub could be a thread that also publishes to the front xsub, v.g. a filter thread in a pipeline connected via a broker implemented by the proxy; it's not difficult to see how this situation could end in a deadlock.

It doesn't seem to be an easy fix because the poll status depends on the message itself: it depends on the topic, which is part of the message. But the polling interface doesn't allow for this AFAIK. Now here are some possible partial fixes:
1. Make has_out throw a not-implemented exception for xpub_nodrop sockets.
2. Make has_out poll every subscriber connected to the xpub. But this will also open the door to deadlocks in the above proxy example, because it introduces cycles in an otherwise linear topology.
3. Impose a sane timeout for xpub_nodrop sockets. The timeout could be silent or throw an exception.
4. Carefully document this behavior both in the xpub_nodrop option documentation and in the proxy documentation.

**Comment by ylow** [comment]
I apologize if I am misunderstanding the issue. But if I understand this correctly, this is an inherent side effect of any "lossless" socket mechanism. The same "faulty" behavior can be achieved with plain TCP sockets. Example: process A is performing communication with process B. If both A and B perform the following simultaneously:

```
    Send Message
    Read Message
```

Then if the message is too large, both processes will block on EAGAIN forever once the TCP buffers are filled (thus interleaving send and receive asynchronously is necessary). (This is also frequently encountered for the same reasons  in  unix stdout pipes since stdout does have a maximum buffer limit).

This issue is true for any use of "lossless" communication channels. For instance if you wrap the ROUTER channel to be "reliable" (i.e. continuously retry with EAGAIN on high water mark), you could very well run into similar issues.

The NODROP option is helpful for a certain design I was working on where I needed reliable broadcast of control messages. If you have complex loops where broadcasts could result in a cascade of more broadcasts, then:
 - If there is no upper limit on the size of the cascade, then you may need infinitely sized buffers and there is something wrong with the overall system. That or you need to drop messages and you shouldn't use NODROP.
 - If there is an upper limit on the size of the cascade, you can size the buffers to allow more than the upper limit.

**Comment by memeplex** [comment]
@ylow I agree with you about the general problem, I'm just saying that poll is wrong in returning always true and that there is no simple way to fix it given that the library design doesn't allow for anything like poll-this-prefix. At least, this should be carefully documented along with the potential proxy/forwarder issues. Anyway, one can implement the poll by doing a nodrop send with 0 timeout (but see https://github.com/zeromq/libzmq/issues/1598).
