### ISSUE TITLE
size of zmq_msg_t is not known to FFI wrappers

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/libzmq#1599]
When writing a FFI wrapper for libzmq you have to guess the size of `zmq_msg_t`

What could help against this is to define a public function to return `sizeof(zmq_msg_t)`, where would be a good place to expose it?

**Comment by hintjens** [comment]
Why can't you just use 'sizeof (zmq_msg_t)' in your code? The type is
defined in zmq.h as a structure.

**Comment by Asmod4n** [comment]
FFI doesn't have access to typedefs made in C, only to functions. The libuv project had a similar issue, so they made functions to return the size of each type they export publicly.

**Comment by hintjens** [comment]
You could try using the zmq_has method.

**Comment by Asmod4n** [comment]
@hintjens zmq_has returns the size of the opaque zmq_msg_t struct?

something like this is needed for FFI wrappers of libzmq:
```c
size_t
zmq_msg_t_size(void)
{
    return sizeof(zmq_msg_t);
}
```

**Comment by Asmod4n** [comment]
FFI doesn't have access to header files, nor can it interpret typedefs, or tell you the size of a opaque struct.

**Comment by hintjens** [comment]
I meant, you could extend zmq_has to return this value. Actually a better
solution: add it to zmq_ctx_get () e.g.

    size = zmq_ctx_get (void *context, ZMQ_MSG_SIZE)

Though it suggests this is variable per context, which is not the case,
it's at least clean for the caller.

**Comment by bjourne** [comment]
Pretty please add this function. I, and the other developers who are working on the Factor language, has spent a huge amount of time (weeks!) debugging an issue which was caused by libzmq increasing the size of the `zmq_msg_t` structure. Our code assumed the old format where the struct was 40 bytes so new versions of libzmq, where the struct is 64 bytes, would cause very hard to debug memory overwrite problems.

Afaict, the libzmq developers idea is that `zmq_msg_t` should be opaque. Users of the library shouldn't need to know details of it so that the format can be updated in the future. That is good engineering practice, but the struct isn't completely opaque because you need to know the size of it to allocate correctly sized buffers. One way to solve it is to add the suggested function `zmq_msg_t_size` which returns the size. Another is for libzmq itself to handle allocation. So for example instead of:

```c
zmq_msg_t *msg = (zmq_msg_t *)malloc(64);
zmq_msg_init_size(msg, 1024);
...
```
You would have functions that return pointers to newly allocated struct instances, like this:
```c
zmq_msg_t *msg = zmq_msg_new_init_size(1024);
...
```
From a FFI writer's perspective the latter variant is much simpler (and safer!) to use.

**Comment by bluca** [comment]
Adding a context read-only option as suggested by Pieter is easy enough, PR coming soon. Note that it might change until the next release and it's considered draft for now. I too prefer the ctx option to using zmq_has.

Breaking the API/ABI would work for FFI bindings but cause enormous problems for other users, so I would rather not do that.
