### ISSUE TITLE
Identify the Queue overload 

### ISSUE THREAD

**Issue by prashantabkari** [zeromq/libzmq#1698]
i am trying to prototype and adapt the ZeroMQ with the current communication framework in the product. Following are the requirement/test cases that i was looking to pass
1. Is it possible to identify the Queue overload
2. Average time spent by messages in the Q

First one is a performance requirement which is required for continuous monitoring should any communication go into an overload condition. 
I have tried setting the ZMQ_RCVHWM and ZMQ_SNDHWM and it works to an extent of dropping the message. But it doesn't indicate a overload scenario. Or is there a way? 

Second one is not a hard requirement but still needed to check in a producer-consumer setup in a multi threaded environment to check the delays and such. 

Any pointers please?

**Comment by metadings** [comment]
You should try `zmq_getsocketopt` for ZMQ_BACKLOG:

	ZMQ_BACKLOG
	Retrieve maximum length of the queue of outstanding connections

	The ZMQ_BACKLOG option shall retrieve the maximum length of the queue of outstanding
 	peer connections for the specified socket; this only applies to connection-oriented transports. 
	For details refer to your operating system documentation for the listen function.
	Option value type 	int
	Option value unit 	connections
	Default value 	100
	Applicable socket types 	all, only for connection-oriented transports

**Comment by prashantabkari** [comment]
Uli - Sorry, doesn't seem the work :-( .  i think this applies for TCP
connections only where in it determines the outstanding connection
messages, based on which it would decide whether to accept further
connections or not.

**Comment by metadings** [comment]
Well... I deleted the comment, also because `ZMQ_BACKLOG` has a default value of `100` so this value won't say something about the Queue's length...

**Comment by hitstergtd** [comment]
@prashantabkari 
I suggest asking this on the `zeromq-dev` list. If your inquiry is fruitful then I suggest updating the issue with the relevant bits for future onlookers.

**Comment by somdoron** [comment]
@prashantabkari none of this is possible.

You can set the send watermark and it will fail to send when the queue is full, now you will be able to see if the queue is full.

The problem is more complex however, queue is exist for every connection, so if you have a router with 1000 dealers connected you have 1000 queues (actually 2000, one for outgoing and one for incoming).

So monitor just doesn't scale here.

If you are doing pub/sub read the pubsub chapter on the guide, there is a way to monitor slow subscribers.

Also if you want to invest a little more you can implement the credit based flow control (google it, I think pieter write an article about that), with credit based flow control you will be able to monitor the performance of each of the connection.

**Comment by hitstergtd** [comment]
@somdoron 
* On that note, I will classify this issue as closed.

@prashantabkari 
* Update this issue with comments as you see fit, to reply to @somdoron, etc.
* If a sufficient case is presented then the issue can be re-opened.

**Comment by prashantabkari** [comment]
@somdoron Yes, i realized that its not supported. But couldn't this be taken up as an enhancement where a monitoring KPI is provided for such Queue handling. The corrective action taken is to drop the message, but wouldn't it be helpful to identify a potential "watermark reaching" situation?

**Comment by somdoron** [comment]
I think it won't help you much, because you probably have a lot of clients connected and some of them will be slower than others. Anyway we can add an event through the monitoring mechanism, the write place to fire the event will be in the pipe class, however I'm not a big fan of this. I think it is better ti detect this in the application level with credit based flow control for example.
