### ISSUE TITLE
[4.1.3] Assertion failed: Successful WSASTARTUP not yet performed (..\..\..\..\src\signaler.cpp:181)

### ISSUE THREAD

**Issue by tomq42** [zeromq/libzmq#1708]
I get this assertion on close down (context close) on Windows, if I put the context in a DLL.

If I create the context inside my main and pass it in to the places it needs it, then the problem goes away.

Note that this is similar to issue #1144, though I believe that the source line number is different, so it appears that that issue is not fully resolved.

**Comment by tomq42** [comment]
Oh, note that I'm using zmq::context_t, just declared as a global variable within my C++ file, so the point is that the close is called from the DLL termination function, on static object destruction.

**Comment by opedroso** [comment]
Same problem also present when running zeromq/malamute tests.
For details how to reproduce, read
https://github.com/zeromq/malamute/issues/169

**Comment by opedroso** [comment]
I was able to make this problem disappear once I made this change in the test itself.
```
x:\3rdparty\malamute>git diff --patch src/mlm_selftest.c
diff --git a/src/mlm_selftest.c b/src/mlm_selftest.c
index 381216f..22c00ed 100644
--- a/src/mlm_selftest.c
+++ b/src/mlm_selftest.c
@@ -141,7 +141,8 @@ main (int argc, char **argv)
     else
         test_runall (verbose);

-    return 0;
+       fcloseall();
+       return 0;
 }
 /*
 ################################################################################
```
Hope it helps somebody fix this issue in LIBZMQ.

**Comment by hitstergtd** [comment]
@opedroso, @tomq42 - thanks for reporting it. Hopefully this can be looked at soon.

**Comment by monsdar** [comment]
Having the same issue with version 4.1.1 - In my case the line number differs a bit. Complete error message: `Assertion failed: Successful WSASTARTUP not yet performed (...\signaler.cpp:171)`

**Comment by diorcety** [comment]
zsys_shutdown() before letting at_exit function to do the job which is called after WSACleanup() ?

**Comment by bjovke** [comment]
@tomq42 Well, maybe you shouldn't use `zmq::context_t` as a global static variable. There are no guarantees in which order will global variables be destructed. It might happen that DLL is unloaded before or in parallel with global variable destruction. You must be sure that you've cleaned up everything before DLL is unloaded. Have you tried localizing your variable?

**Comment by bjovke** [comment]
@monsdar Even if libzmq is used as a static lib, you're still using winsock.dll or ws2_32.dll. These DLLs might have already started cleanup and unloading before context is destroyed, the same as if they called `WSACleanup()` on their own.

I think this is not libzmq issue because compiler offers no guarantees that destructor for context will be called **before** DLL unloading. Also the C++ standard does not offer these guarantees on any platform as far as I know.

If you are able to use C++11 I suggest using `std::shared_ptr<zmq::context_t>` instead of `zmq::context_t` as a global variable. This guarantees that context is cleaned up on exit from the last function using this variable, before any global deallocations start to happen. If you're not able to use C++11 you could still write your own simple shared pointer.

**Comment by xudonglei** [comment]
You have solved the problem @bjovke
