### ISSUE TITLE
cannot build with tweetnacl on OS X

### ISSUE THREAD

**Issue by minrk** [zeromq/libzmq#1781]
- tweetnacl config is only supported when using cmake
- the cmake builds don't work on OS X

**Comment by hintjens** [comment]
It would be great to get some temporary OS X hosting to play with.

We don't support tweetnacl in autotools, do we?

**Comment by minrk** [comment]
#1782 adds tweetnacl support in autotools

We could run OS X builds on Travis

**Comment by bluca** [comment]
We do have OSX builds :-)

I'll try and add a tweetnacl build and a cmake build to the CI, if they are stable I'll send a PR

**Comment by bluca** [comment]
Where do we get the tweetnacl source from? There's this warning:

`  CXX    src/src_libzmq_la-ctx.lo
In file included from src/ctx.cpp:52:0:
./tweetnacl/contrib/randombytes/randombytes.h:14:41: error: ISO C++ 1998 does not support ‘long long’ [-Werror=long-long]`

Would be easy to fix, but it's best to check upstream first

**Comment by hintjens** [comment]
I'd suggest fixing in our fork of the source and then we can send a patch
to https://tweetnacl.cr.yp.to/

**Comment by bluca** [comment]
So that header doesn't come from tweetnacl (although it's used in there), but it's a snippet from the original crypto stuff from nacl, by D. J. Bernstein. I _really_ don't think it's a good idea to go in there and change types :-)

Instead, I'll do what we already do for OSX builds and disable -pedantic for tweenacl builds.

Incidentally, do we keep building for C99/C++98 for a particular reason, or is it just that no one bothered to up it?
