### ISSUE TITLE
Sample Application Bug

### ISSUE THREAD

**Issue by lafual** [zeromq/libzmq#1787]
On [zguide.zeromq.org/java:lvcache](http://zguide.zeromq.org/java:lvcache)

I think that;
`frontend.bind("tcp://*:5557");`

... should read ...

`frontend.connect("tcp://*:5557");`

... because the Publisher ([zguide.zeromq.org/java:pathopub](http://zguide.zeromq.org/java:pathopub)) is already bound to this port and the Cache should be reading from it.

**Comment by hintjens** [comment]
Send a pull request with a fix, could you?

**Comment by UsamaMehboob** [comment]
Its in python as well as java, shoul I send a pull request after fixing both?

**Comment by hintjens** [comment]
Sure

**Comment by hitstergtd** [comment]
@hintjens We can probably close this off since the changes are already in zguide.

**Comment by metadings** [comment]
This is wrong, I need to revert this.

- You can't `frontend.connect("tcp://*:5557")` just because of the address `*`.

1. Usually PathoPub is binding PUB on 5556, PathoSub is connecting SUB to 5556.

2. Using LVCache, which is binding SUB on 5557 and is binding XPUB on 5558,
you can now use PathoPub, to connect PUB to 5557,
and PathoSub, to connect SUB to 5558.

**Comment by metadings** [comment]
I believe you found an error, which is that [Java's PathoPub](https://github.com/imatix/zguide/blob/master/examples/Java/pathopub.java#L16) does bind `args[0]` - but instead this has to connect to `args[0]`. This error is also in the [C's PathoPub](https://github.com/imatix/zguide/blob/master/examples/C/pathopub.c#L11).
