### ISSUE TITLE
PUSH sockets should exhibit consistent blocking behaviour

### ISSUE THREAD

**Issue by mato** [zeromq/libzmq#179]
In issue 130, the reporter has found that the documentation for how PUSH sockets behave when no downstream nodes are connected is inconsistent with the actual implementation.

What should be done is that the behaviour needs to be consistent (send blocks if no downstream peers connected) whether or not the endpoint has been created with zmq_bind() or zmq_connect().

This may also affect other socket types.

Martin Sustrik's suggestion is to create a pre-prepared pipe on bind so that flow control can be applied, and then assign this pipe to the first connected peer.

**Comment by chrisjbillington** [comment]
Either this issue was not resolved, or I am seeing a regression. In pyzmq 18.0.1 with libzmq 4.3.1 on Linux, I see that the following blocks on `send`:

```python
import zmq
sock = zmq.Context.instance().socket(zmq.PUSH)
sock.bind('tcp://127.0.0.1:8888')
print('about to send')
sock.send(b'hello')
print('sent')
```

Whereas changing the `bind` to `connect` causes it to not block.

Another developer of a project I work on (in which we have a bug that led me to discover this behaviour) observed the issue on Windows as well, though I don't know the exact library versions.

Could the issue be reopened?

**Comment by chrisjbillington** [comment]
Since I'm not sure if anyone still active in the project is subscribed to this bug report, tagging @bluca to consider re-opening the bug report (see above comment for why).

**Comment by chrisjbillington** [comment]
I think I misunderstood the bug report. I thought the problem was that PUSH could block when no peers are connected. But this is apparently documented behaviour and not the bug. The bug is that PUSH does *not* block when it calls `connect` rather than `bind`.

My issue was the blocking sends after `bind`. It seems I will have to either `send` in a separate thread to block without blocking the main thread of my app, or I will have to retry in a loop periodically. Both of these aren't really 'the zeromq way', it would be nice if there were a way to queue messages to be sent prior to peers connecting.

Anyway I'll treat this as an issue for my application for now.
