### ISSUE TITLE
zmq_poll can't poll for reading on SERVER sockets

### ISSUE THREAD

**Issue by paddor** [zeromq/libzmq#1868]
As far as I know, this used to work. Calling `zmq_poll` on a `poll_item_t` for a SERVER socket now fails in EINVAL. It works fine on PULL sockets.

Discovered in paddor/cztop#1.

**Comment by paddor** [comment]
Now I'm not so sure anymore whether it worked before.

But as far as I can remember, at least polling for reading on a SERVER (or CLIENT) socket should work using the `zmq_poll` interface. Am I wrong?

**Comment by somdoron** [comment]
Only zmq_poller support thread-safe (client,server,radio,dish) sockets.
Czmq zpoller already using zmq_poller

**Comment by hintjens** [comment]
@somdoron we need to start thinking about how to document this new draft API.

* I'd like to mark it as DRAFT the same way as we do with zproject APIs, so we can include it in a stable 4.2 release.
* We could generate man pages using an approach similar to zproject/CZMQ. Otherwise, we need to make a man page by hand for each method. (Not so nice IMO).

Thoughts?

**Comment by somdoron** [comment]
So you want to generate the entire zmq.h file along with docs? so we need to make zmq.xml file. That is a lot of work, to take all current documentation and zmq.h and create an xml file. Anyway, I like it.

**Comment by hintjens** [comment]
We scrape the man pages from the source, so could adapt that for zmq.h...
No need to define API models

**Comment by hintjens** [comment]
I've started a separate issue: #1876

**Comment by paddor** [comment]
@somdoron Thanks for the info. I guess I'll use `zmq_poller_*()` then, since zpoller can only poll for reading.
