### ISSUE TITLE
ZMQ_SERVER sends corrupt response if multiple clients are connected

### ISSUE THREAD

**Issue by rhymerjr** [zeromq/libzmq#2055]
I'm wondering that maybe i'm doing something wrong but it is a very strange thing what I see,
If multiple ZMQ_CLIENT are connected to the same ZMQ_SERVER the response sent back by the server looks corrupt in some cases.
Also i'm confused with the usage of zmq_msg_set_routing_id()! Which side must set it first?

SERVER CODE:

    while(true)
    {
        //BULKIF_COMM::BLK blk; // main message container
        zmq_msg_t msg;
        zmq_msg_init (&msg);
        int bytecnt;
        if (0<(bytecnt=zmq_msg_recv (&msg, server, 0)))
        {
            uint32_t routing_id = zmq_msg_routing_id (&msg);
            printf("INSTANCE %s PROCESS - RECV %i bytes\n",instance_name.c_str(),bytecnt);
            BULKIF_COMM::BLK blk; // main message container
            std::string s_msg;
            s_msg.assign((char*)zmq_msg_data(&msg),bytecnt);
            if ( blk.ParseFromString(s_msg))
            {
                if (blk.has_mtype())
                {
                    printf("INSTANCE %s PROCESS - MSG IS: %s\n",instance_name.c_str(),blk.DebugString().c_str());
                    std::string s_reqtoken=blk.req().reqtoken(); // for testings
                    int errc=blk.req().page(); // for testings
                    blk.Clear(); // empty parsed obj
                    // SEND BACK
                    blk.set_mtype(blk.BLK_RES); // set msg type to response
                    blk.mutable_res(); // init res field
                    blk.mutable_res()->set_reqwas(s_reqtoken); // set values
                    blk.mutable_res()->set_errc(errc);
                    blk.mutable_res()->set_errm("ERR MSG HERE");
                    blk.mutable_res()->set_reqtoken(s_reqtoken);
                    
                    std::string s_msgr; // string to serialize into
                    blk.SerializeToString(&s_msgr); // serialize
                    
                    zmq_msg_t msgr;
                    zmq_msg_init_data (&msgr, (void*)s_msgr.data(), s_msgr.size(), NULL, NULL);
                    zmq_msg_set_routing_id (&msgr, routing_id);
                    int sentbytes=zmq_msg_send (&msgr, server, 0);
                    zmq_msg_close(&msgr);
                    if (0<sentbytes)
                    {
                        printf("INSTANCE %s PROCESS - SEND SUCCESS(%i) \n",instance_name.c_str(),sentbytes);
                        printf("INSTANCE %s PROCESS - SENT: %s \n",instance_name.c_str(),blk.DebugString().c_str());
                    }
                    else
                    {
                        printf("INSTANCE %s PROCESS - ERROR - SEND FAILED\n",instance_name.c_str());
                    }
                }
                else
                {
                    printf("INSTANCE %s PROCESS - ERROR - FIELD mtype IS MISSING\n",instance_name.c_str());
                }
            }
            else
            {
                printf("INSTANCE %s PROCESS - ERROR - FAILED TO ParseFromCodedStream\n",instance_name.c_str());
            }
        }
        else
        {
            // 0 = NO MSG RECEIVED, -1 ERROR ON RECV
        }
        zmq_msg_close (&msg);
    }
    zmq_close (server);
    zmq_ctx_destroy (context);

CLIENT CODE:

    std::random_device rd; // obtain a random number from hardware
    std::mt19937 eng(rd()); // seed the generator
    std::uniform_int_distribution<> distr(100, 999); // define the range
    uint32_t routing_id=distr(eng);
    while( !mustExit )
    {
        request_nbr++;
        std::string s_cnt=std::to_string(request_nbr);
        int i_mag=request_nbr;
        int i_page=request_nbr;

        BULKIF_COMM::BLK blk; // main message container
        blk.set_mtype(blk.BLK_REQ);
        blk.mutable_req();
        blk.mutable_req()->set_rtype(blk.mutable_req()->WRITE);
        blk.mutable_req()->set_mag(i_mag);
        blk.mutable_req()->set_page(i_page);
        blk.mutable_req()->set_wsp("CONTENT");
        blk.mutable_req()->set_reqtoken(instance_name+myhelpers::helpers::time_getNow());

        std::string s_msg;
        blk.SerializeToString(&s_msg);

        zmq_msg_t msg;
        zmq_msg_init_data (&msg, (void*)s_msg.data(), s_msg.size(), NULL, NULL); // PROTOBUF - WAS OK
        zmq_msg_set_routing_id (&msg, routing_id);
        int sentbytes=zmq_msg_send (&msg, client, 0);
        zmq_msg_close(&msg);

        if (0<sentbytes)
        {
            printf("INSTANCE %s PROCESS - SEND SUCCESS(%i) \n",instance_name.c_str(),sentbytes);
        }
        else
        {
            printf("INSTANCE %s PROCESS - ERROR - SEND FAILED\n",instance_name.c_str());
        }

        // RECV
        blk.Clear();

        zmq_msg_init (&msg);
        int bytecnt;
        bytecnt=zmq_msg_recv (&msg, client, 0);
        if ( 0<bytecnt )
        {
            std::string s_msg;
            s_msg.assign((char*)zmq_msg_data(&msg),bytecnt);
            if ( blk.ParseFromString(s_msg))
            {
                if (blk.has_mtype())
                {
                    printf("INSTANCE %s PROCESS - RECV MSG IS(%i): %s\n",instance_name.c_str(),bytecnt,blk.DebugString().c_str());
                }
                else
                {
                    printf("INSTANCE %s PROCESS - ERROR - RECV - FIELD mtype IS MISSING\n",instance_name.c_str());
                }
            }
            else
            {
                printf("INSTANCE %s PROCESS - ERROR - RECV - FAILED TO ParseFromCodedStream\n",instance_name.c_str());
            }
            zmq_msg_close(&msg);
        }
        if (request_nbr>(imax-1)) request_nbr=1;
    }
    zmq_disconnect (client, "tcp://10.38.200.188:6661");
    zmq_close (client);
    zmq_ctx_destroy (context);

If one client is working then everything works just fine!
But right after the second client has been connected to the same server and started to work
I see the error messages by both clients in some cases NOT all the time but really frequently: 

"./p_client_base | grep ERROR
INSTANCE CLIENT PROCESS - ERROR - RECV - FAILED TO ParseFromCodedStream
INSTANCE CLIENT PROCESS - ERROR - RECV - FAILED TO ParseFromCodedStream
INSTANCE CLIENT PROCESS - ERROR - RECV - FAILED TO ParseFromCodedStream
..
...
... "

There is no ERROR by the server process no matter how many clients are connected to it,
so something happens when the server sends the response back to the clients I think.

What could be the problem?

libzmq built from the actually Master branch!

**Comment by somdoron** [comment]
You dont need to set routing id on the client.

Regarding your issue, it seems you are using std-string internal buffer for
sending,  however it get deallocate everytime you exit the scope,  I think
this causing your error.  Call init size instead and copy the data to the
msg structure..

I'm wondering that maybe i'm doing something wrong but it is a very strange
thing what I see,
If multiple ZMQ_CLIENT are connected to the same ZMQ_SERVER the response
sent back by the server looks corrupt in some cases.
Also i'm confused with the usage of zmq_msg_set_routing_id()! Which side
must set it first?

SERVER CODE:

while(true)
{
    //BULKIF_COMM::BLK blk; // main message container
    zmq_msg_t msg;
    zmq_msg_init (&msg);
    int bytecnt;
    if (0<(bytecnt=zmq_msg_recv (&msg, server, 0)))
    {
        uint32_t routing_id = zmq_msg_routing_id (&msg);
        printf("INSTANCE %s PROCESS - RECV %i
bytes\n",instance_name.c_str(),bytecnt);
        BULKIF_COMM::BLK blk; // main message container
        std::string s_msg;
        s_msg.assign((char*)zmq_msg_data(&msg),bytecnt);
        if ( blk.ParseFromString(s_msg))
        {
            if (blk.has_mtype())
            {
                printf("INSTANCE %s PROCESS - MSG IS:
%s\n",instance_name.c_str(),blk.DebugString().c_str());
                std::string s_reqtoken=blk.req().reqtoken(); // for testings
                int errc=blk.req().page(); // for testings
                blk.Clear(); // empty parsed obj
                // SEND BACK
                blk.set_mtype(blk.BLK_RES); // set msg type to response
                blk.mutable_res(); // init res field
                blk.mutable_res()->set_reqwas(s_reqtoken); // set values
                blk.mutable_res()->set_errc(errc);
                blk.mutable_res()->set_errm("ERR MSG HERE");
                blk.mutable_res()->set_reqtoken(s_reqtoken);

                std::string s_msgr; // string to serialize into
                blk.SerializeToString(&s_msgr); // serialize

                zmq_msg_t msgr;
                zmq_msg_init_data (&msgr, (void*)s_msgr.data(),
s_msgr.size(), NULL, NULL);
                zmq_msg_set_routing_id (&msgr, routing_id);
                int sentbytes=zmq_msg_send (&msgr, server, 0);
                zmq_msg_close(&msgr);
                if (0<sentbytes)
                {
                    printf("INSTANCE %s PROCESS - SEND SUCCESS(%i)
\n",instance_name.c_str(),sentbytes);
                    printf("INSTANCE %s PROCESS - SENT: %s
\n",instance_name.c_str(),blk.DebugString().c_str());
                }
                else
                {
                    printf("INSTANCE %s PROCESS - ERROR - SEND
FAILED\n",instance_name.c_str());
                }
            }
            else
            {
                printf("INSTANCE %s PROCESS - ERROR - FIELD mtype IS
MISSING\n",instance_name.c_str());
            }
        }
        else
        {
            printf("INSTANCE %s PROCESS - ERROR - FAILED TO
ParseFromCodedStream\n",instance_name.c_str());
        }
    }
    else
    {
        // 0 = NO MSG RECEIVED, -1 ERROR ON RECV
    }
    zmq_msg_close (&msg);
}
zmq_close (server);
zmq_ctx_destroy (context);

CLIENT CODE:

std::random_device rd; // obtain a random number from hardware
std::mt19937 eng(rd()); // seed the generator
std::uniform_int_distribution<> distr(100, 999); // define the range
uint32_t routing_id=distr(eng);
while( !mustExit )
{
    request_nbr++;
    std::string s_cnt=std::to_string(request_nbr);
    int i_mag=request_nbr;
    int i_page=request_nbr;

    BULKIF_COMM::BLK blk; // main message container
    blk.set_mtype(blk.BLK_REQ);
    blk.mutable_req();
    blk.mutable_req()->set_rtype(blk.mutable_req()->WRITE);
    blk.mutable_req()->set_mag(i_mag);
    blk.mutable_req()->set_page(i_page);
    blk.mutable_req()->set_wsp("CONTENT");
    blk.mutable_req()->set_reqtoken(instance_name+myhelpers::helpers::time_getNow());

    std::string s_msg;
    blk.SerializeToString(&s_msg);

    zmq_msg_t msg;
    zmq_msg_init_data (&msg, (void*)s_msg.data(), s_msg.size(), NULL,
NULL); // PROTOBUF - WAS OK
    zmq_msg_set_routing_id (&msg, routing_id);
    int sentbytes=zmq_msg_send (&msg, client, 0);
    zmq_msg_close(&msg);

    if (0<sentbytes)
    {
        printf("INSTANCE %s PROCESS - SEND SUCCESS(%i)
\n",instance_name.c_str(),sentbytes);
    }
    else
    {
        printf("INSTANCE %s PROCESS - ERROR - SEND
FAILED\n",instance_name.c_str());
    }

    // RECV
    blk.Clear();

    zmq_msg_init (&msg);
    int bytecnt;
    bytecnt=zmq_msg_recv (&msg, client, 0);
    if ( 0<bytecnt )
    {
        std::string s_msg;
        s_msg.assign((char*)zmq_msg_data(&msg),bytecnt);
        if ( blk.ParseFromString(s_msg))
        {
            if (blk.has_mtype())
            {
                printf("INSTANCE %s PROCESS - RECV MSG IS(%i):
%s\n",instance_name.c_str(),bytecnt,blk.DebugString().c_str());
            }
            else
            {
                printf("INSTANCE %s PROCESS - ERROR - RECV - FIELD
mtype IS MISSING\n",instance_name.c_str());
            }
        }
        else
        {
            printf("INSTANCE %s PROCESS - ERROR - RECV - FAILED TO
ParseFromCodedStream\n",instance_name.c_str());
        }
        zmq_msg_close(&msg);
    }
    if (request_nbr>(imax-1)) request_nbr=1;
}
zmq_disconnect (client, "tcp://10.38.200.188:6661");
zmq_close (client);
zmq_ctx_destroy (context);

If one client is working then everything works just fine!
But right after the second client has been connected to the same server and
started to work
I see the error messages by both clients in some cases NOT all the time but
really frequently:

"./p_client_base | grep ERROR
INSTANCE CLIENT PROCESS - ERROR - RECV - FAILED TO ParseFromCodedStream
INSTANCE CLIENT PROCESS - ERROR - RECV - FAILED TO ParseFromCodedStream
INSTANCE CLIENT PROCESS - ERROR - RECV - FAILED TO ParseFromCodedStream
..
...
... "

There is no ERROR by the server process no matter how many clients are
connected to it,
so something happens when the server sends the response back to the clients
I think.

What could be the problem?

libzmq built from the actually Master branch!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zeromq/libzmq/issues/2055>, or mute the thread
<https://github.com/notifications/unsubscribe/AClv9rVwvizZlzdFT_LISqEn0RMPyIe3ks5qS8MrgaJpZM4JGLE2>
.

**Comment by rhymerjr** [comment]
zmq_msg_set_routing_id() is now clear for me!

And you were right! After i replaced zmq_msg_init_data() with zmq_msg_init_size() and memcpy()
everything works fine without any errors!

Also it is clear now that the message still has the content as reference to that external string when the message is awaiting for transmission in the internal queue and my loop was faster than zmq could be sent the message out.

Thank you for your help it was really helpful!

**Comment by somdoron** [comment]
You are welcome.

Can we close the issue?

**Comment by rhymerjr** [comment]
Yes of course!
Thanks!
