### ISSUE TITLE
Add release tags for releases and use GitHub's release feature

### ISSUE THREAD

**Issue by torbjoernk** [zeromq/libzmq#2079]
It would be awesome to use Git's tags for labeling released versions. As well, you could facilitate GitHub's release feature to add some info (e.g. lists of notable changes) to major releases.

For now, there is no way to know which commit represents the state of a specific release, e.g. 4.1.5.

**Comment by bluca** [comment]
We already do, in fact we recently implemented Github + Travis release artefacts.
Historically a major release resulted in a fork, and that's why there are intentionally no tags on this repository. This will possibly change for the next major release.
You can find the release tags in their respective repositories:
https://github.com/zeromq/zeromq4-1
https://github.com/zeromq/zeromq4-x
And so on.
