### ISSUE TITLE
Platform-specific packaging files should be in a separate repository

### ISSUE THREAD

**Issue by aalex** [zeromq/libzmq#2087]
Hi,
Debian and Fedora platform-specific files, among others, should not be in this repository. For a given release, the packagers might store a series of proposed patches to the upstream source code, but should never modify the upstream source code repository directly. The upstream developers should create a tag, and then the platform-specific packaging should happen, using that tarball as an upstream source.

**Comment by bluca** [comment]
Hi,

The packaging is not part of the dist release tarball, intentionally. It will have no effect on downstream packagers since it's not included. You can verify that easily by running make dist and checking the content of the tarball.

It is added to the repository so that we can deploy packages for RHEL/Centos/SUSE/Fedora/Ubuntu/Debian automatically from the latest commit on each push via OBS:

https://build.opensuse.org/package/show/home:zeromq:libzmq/libzmq
