### ISSUE TITLE
testutils won't compile when targeting windows xp

### ISSUE THREAD

**Issue by CommanderBubble** [zeromq/libzmq#2091]
under windows xp, inet_pton is not available, so testutils will not build, erroring on line 339.

additionally, inet_addr is only available for ipv4 addresses, so we don't have access to this method for converting the string to an address for pre-vista systems. (http://msdn.microsoft.com/en-us/library/windows/desktop/ms738563(v=vs.85).aspx)

**Comment by bluca** [comment]
The joys of Windows. Sigh. Could you please test this branch for me (I don't have a Windows XP box available):

https://github.com/bluca/libzmq/tree/xp_testutils_ipv6

**Comment by bluca** [comment]
There are other instances checking the WINNT version in the code, in other tests as well, test_heartbeats.cpp has the exact same problem with inet_pton for example, so that should be fine.

This is just a test, and in that a utility function used to try and detect if IPv6 is available, that is used by one test. I created it for use in our CI system on Travis more than anything else. It will not impact any functionality.

**Comment by CommanderBubble** [comment]
it was more just musing that if ipv6 is available, then we are saying it isn't because we haven't checked.

regardles, just built that branch as well as moving those changes in stable 4.1.5, which is what i was compiling when i found it, and it is able to build, and build the tests as well. though quite a few (18) tests fail, but i assume that is unrelated to this.

**Comment by bluca** [comment]
Given XP is EOL I'm not too fussed about skipping that test on it :-)
Thanks for the feedback, I've opened a PR and will backport it to zeromq4-1 once merged here.
