### ISSUE TITLE
Problem: binding tcp://127.0.0.1:* with IPv6 enabled fails on Windows

### ISSUE THREAD

**Issue by bluca** [zeromq/libzmq#2124]
```
Assertion failed: rc == 0, file C:\projects\libzmq\tests\test_unbind_wildcard.cpp, line 151
```

```
    /* Port wildcard, IPv4 address, IPv6 enabled */
    sb = zmq_socket (ctx, ZMQ_REP);
    assert (sb);

    rc = zmq_setsockopt (sb, ZMQ_IPV6, &ipv6, sizeof (int));
    assert (rc == 0);

    rc = zmq_bind (sb, "tcp://127.0.0.1:*");
    assert (rc == 0);
```

https://libzmq.cloudapp.net/job/libzmq/1249/console
https://ci.appveyor.com/project/zeromq/libzmq/build/build-740/job/57w8q8y8hqnb1d2r

Does any Windows developer have an idea why this might be failing and/or have time to debug it?

AFAIK it's the last test to fix to get a clean pass on Windows, so blocks #1903

**Comment by t-b** [comment]
@bluca getaddrinfo in line 327 of tcp_address.cpp returns 11001.

**Comment by bluca** [comment]
Is there anything else we can do apart from removing AI_NUMERICHOST if building on windows?

**Comment by soulik** [comment]
It fails because of "getaddrinfo" function behaviour on Windows platform.
This function makes a use of "address hints" structure containing "address family" identifier. It basically tells OS if you expect IPv4 or IPv6 address structure in return.
Now if you try to bind to 127.0.0.1 with IPv6 option enabled, it won't find any address info you expected and therefore returns code 11001 - WSAHOST_NOT_FOUND.

I've added fallback mechanism for this specific case in f696290 commit. Please, test it in your environment and let me know how it went.

**Comment by bluca** [comment]
Thanks again for sending the PR @soulik the Windows CI tests are now almost always green (test_xpub_nodrop occasionally and seemingly randomly fails, but that's a separate issue).
