### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [zeromq/libzmq#2154]
I would like to point out that an identifier like "[`__ZMQ_H_INCLUDED__`](https://github.com/zeromq/libzmq/blob/de7fc1fcf850ab44eb33b6a285f2a455dde67e73/include/zmq.h#L38)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by c-rack** [comment]
Yes, please send a PR to fix it, thanks!

**Comment by bluca** [comment]
The public header is used also in C, not only C++, and changing it now could have unintended consequences. Closing.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by sigiesec** [comment]
@bluca I can't relate your comment to the issue. Identifiers starting with _ are also reserved in C: https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier

I also don't see how changing this could have unintended consequences. Libzmq uses other macros starting with ZMQ_, so it should also be possible to use a header guard starting with ZMQ_, which resolves this issue.

**Comment by bluca** [comment]
Consider a spaghetti project (I've seen things...) that due to recursive inclusion ends up with multiple versions of libzmq in the preprocessor path - right now it works as we have been ABI and API compatible for years. Changing the include guards means they will suddenly start failing to build.

It's not worth the risk, as I'm pretty sure the ISO committee(s) are not going to add __ZMQ keywords or identifiers to the language(s)...

**Comment by sigiesec** [comment]
I agree that this is probably not a high priority with respect to the direct consequences I can imagine.

However, the point is not that the __ZMQ* identifier will be assigned a specific meaning in the C or C++ standard (this is indeed very unlikely), but that it is reserved for use by a compiler implementation. I cannot really imagine that some other consequence except for a broken build results (for example because the compiler happens to generate exactly this identifier from the header file name for some internal use), but "undefined behaviour" allows a compiler implementation to be fully C or C++ compliant and just generate garbage code when such an identifier is present in user code.

IMO the main point is that it would be good to be able to claim that zmq.h is compliant with the C standard at least with respect to UB without exception, which could not be claimed in the current state. Policies of users might require this.

And while I can imagine such a situation as you describe, this is something that demands a fix on the spaghetti project side. I don't think it is a good idea to try to support such broken uses.
