### ISSUE TITLE
Build fails if path contains spaces

### ISSUE THREAD

**Issue by lgeiger** [zeromq/libzmq#2211]
We're using libzmq 4.2.0 and built it with
```
./autogen.sh
./configure "--prefix=/Users/lukasgeiger/code/zmq prebuilt/scripts/../zmq" --with-relaxed --enable-static --disable-shared
make -j 2
make install
```

If the prefix path contains spaces, the build fails with the following error:
```
make[2]: Nothing to be done for `install-exec-am'.
 config/install-sh -c -d '/Users/lukasgeiger/code/zmq prebuilt/scripts/../zmq/lib'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   src/libzmq.la '/Users/lukasgeiger/code/zmq prebuilt/scripts/../zmq/lib'
libtool: install: /usr/bin/install -c src/.libs/libzmq.lai /Users/lukasgeiger/code/zmq prebuilt/scripts/../zmq/lib/libzmq.la
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make[2]: *** [install-libLTLIBRARIES] Error 64
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
child process exited with code 2
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/zmq.node
clang: error: no such file or directory: './Release/../../zmq/lib/libzmq.a'
make: *** [Release/zmq.node] Error 1
```

It looks like the path passed to `libtool: install: /usr/bin/install -c src/.libs/libzmq.lai ` isn't wrapped in quotes.

**Comment by bluca** [comment]
Could you please send a PR to fix it?

**Comment by lgeiger** [comment]
@bluca I tried but couldn't find the relevant line causing the problem.

**Comment by bluca** [comment]
I did a bit of digging, and as far as I can see unfortunately there's nothing we can do, I'm sorry.
This is not an issue with our use of autotools, but a bug in libtool, which will not be fixed by the developers:

https://lists.gnu.org/archive/html/bug-automake/2007-10/msg00005.html
https://sourceware.org/ml/binutils/2010-10/msg00204.html

If a path without spaces cannot be avoided, then I would suggest switching to CMake, as it supports it.
Supporting CMake is the best we can do I'm afraid.

Given there's nothing we can do I'll close this for housekeeping, but if you (or any other) find out a way to work around the libtool bug or a similar solution please do reopen this issue.
