### ISSUE TITLE
Problem: Windows does not support IPV6_TCLASS

### ISSUE THREAD

**Issue by myseemylife** [zeromq/libzmq#2229]
IPV6_TCLASS in ip.cpp is not defined!
what values should i define it?

**Comment by bluca** [comment]
Support for IPV6_TCLASS was added recently, but we missed that Windows does not support it.

Apparently there's a Windows-specific API for ToS, because standards:
https://support.microsoft.com/en-us/kb/248611
https://msdn.microsoft.com/en-us/library/windows/desktop/bb960848(v=vs.85).aspx

I'll fix the build error now, and if anyone needs ToS on Windows they'll have to implement support for these APIs I'm afraid

**Comment by bluca** [comment]
I do wonder why neither appveyor nor jenkins CIs catched this...

**Comment by bluca** [comment]
@myseemylife please try again from the HEAD of master, should be good now
