### ISSUE TITLE
Visual Studio: no way to check if libzmq was compiled with draft api

### ISSUE THREAD

**Issue by Asmod4n** [zeromq/libzmq#2307]
On Unix like systems pkg-config can tell you if libzmq was compiled with ZMQ_BUILD_DRAFT_API, cannot find something like that for Visual Studio on Windows.

Was there a reason zmq.h isn't adapting for it? (Leave all draft api declarations out if they aren't enabled)

**Comment by bluca** [comment]
Can't VS support different "configuration" types? I know there's "release" and "debug". Wouldn't that be the better way to implement something like this?

**Comment by Asmod4n** [comment]
If there is a runtime option to check if one is using libzmq from a "draft" build that would be ok.

**Comment by bluca** [comment]
Can't those mechanism add compiler flags? I would imagine things like optimization or debugging symbols need to be added at compile time

**Comment by Asmod4n** [comment]
That would be good too :)

**Comment by Asmod4n** [comment]
Or no, those compiler flags would have to be added to all projects, or it cannot be checked outside of the libzmq build(?)

At the moment you have to guess if the draft api is enabled and see if the linker returns a error.

**Comment by evoskuil** [comment]
@bluca VS configurations exist, but the chosen configuration is not registered in a central location in the operating system after a build (unlike pkg-config).

The proper way to expose a build option in a vs project is to define a property, which then becomes selectable in the VS IDE. A VS configuration (like the Release and Debug configurations I have defined) is just a named collection of such properties.

But there is no mechanism to project the result of one build as a dependency of a dependent build. This is something that requires a registry such as provided by package config. But that of course produces problems where registered builds produce conflicts. For example, someone builds a lib with a certain configuration (e.g. dynamic) and a dependent package needs a different configuration (e.g. static). So pkg-config is really not a solution either. I now only use pkg-config in a prefix directory in which I build and register all dependencies, coordinating their configuration via a generated installer. Otherwise build breaks are a constant problem.

So with VS it amounts to the same thing. Something external must coordinate the build configurations. This is easily accomplished on the build command line, as long as configuration options are properly exposed as properties. This is where xplat projects tend to break VS conventions (since they aren't generally understood) and get ugly. This is the analogy to the proper use of autotools configure.

**Comment by Asmod4n** [comment]
What about just simply adding "draft" to zmq_has?

**Comment by Asmod4n** [comment]
Oh, there is another issue.
The draft api cannot be used with ffi

**Comment by bluca** [comment]
@Asmod4n that sounds sensible, would you send a PR to implement it?

@evoskuil so the suggestion would be to generate the public header rather than having ifdefs? That shoulds sensible too, although it's going to be a bit of work to implement that for all build systems

**Comment by evoskuil** [comment]
@bluca Sorry, I'm not sure I understand what you are proposing.

**Comment by Asmod4n** [comment]
@bluca as it looks like, ZMQ_BUILD_DRAFT_API is always defined, even when you compile it without it, as such a zmq_has option doesn't work..

**Comment by bluca** [comment]
How can that be? If that were the case then the symbols would always be available

**Comment by Asmod4n** [comment]
Ah, yes and no: https://github.com/zeromq/libzmq/blob/master/src/zmq_draft.h#L38 https://github.com/zeromq/libzmq/blob/master/src/precompiled.hpp#L44 https://github.com/zeromq/libzmq/blob/master/src/zmq.cpp#L38

**Comment by bluca** [comment]
Still can't be or there would be double definitions from zmq.h and zmq_draft.h.
Are you sure you are not referring to a windows-specific hack in those project files?

**Comment by Asmod4n** [comment]
zmq_draft.h checks if ZMQ_BUILD_DRAFT_API is not defined, while zmq.h checks if ZMQ_BUILD_DRAFT_API is defined.

**Comment by bluca** [comment]
Yes and if the symbol was always there internally the functions in zmq_draft would never be declared, so the build would fail

**Comment by Asmod4n** [comment]
Ill just wait till the draft Api gets stable for Windows and update the dependency to libzmq 4.3 of my project then.

**Comment by wchengad** [comment]
@Asmod4n @bluca I want to transfer the old version of libzmq to the latest version and enable drafts to transfer data via UDP between a Linux and another Windows computer. I wonder how can I enable draft in msvc builds. I tried to build dynamic lib in default setting, and zmq_has("draft") returned a non-1 value which means draft was disabled.

**Comment by evoskuil** [comment]
I believe the draft switch is available in the MSCV UI extensions. This means it is also exposed as a command line build property.

**Comment by wchengad** [comment]
@evoskuil Yeah, the draft switch in msvc is in the properties setting UI of the solution.
