### ISSUE TITLE
Different name for the static library between cmake and [configure + make]

### ISSUE THREAD

**Issue by SylvainCorlay** [zeromq/libzmq#2310]
The name of the static library generated by cmake is `libzmq-static/[a|lib]` while the regular makefile creates `libzmq.[a|lib]`.

Ping @JohanMabille @minrk.

**Comment by JohanMabille** [comment]
@SylvainCorlay @minrk 

The problem is building with cmake generates both static and dynamic libraries, and they can't have the same name on Windows (because dynamic link on windows also requires a .lib).

So two options here:

- we forbid simultaneous static and dynamic builds
- we keep the ` libzmq-static` name for Windows only

Both will break build backward compatibility
