### ISSUE TITLE
Build VS2010 - LINK : fatal error LNK1104: cannot open file 'libzmq.lib'

### ISSUE THREAD

**Issue by dcube9** [zeromq/libzmq#2341]
Hi,
during build versione 4.2.1 with VS2010 (Both Batch and VStudio) error LNK1104 occours in all "perf" tools.
To fix the problem : modify paths in AdditionalLibraryDirectories and SourceFiles of file **.....builds\msvc\vs2015\libzmq.import.props**

**AdditionalLibraryDirectories**
Original : `$(ProjectDir)..\..\..\..\..\libzmq\bin\$(PlatformName)\Debug\$(PlatformToolset)\$(Linkage-libzmq)\`
Modify in : `$(ProjectDir)..\..\..\..\bin\$(PlatformName)\Debug\$(PlatformToolset)\$(Linkage-libzmq)\`

**SourceFiles in Target Name="Linkage-libzmq-dynamic"**
All : `$(ProjectDir)..\..\..\..\..\libzmq\bin\$(PlatformName)\Debug\$(PlatformToolset)\dynamic\`
Modify in : `$(ProjectDir)..\..\..\..\bin\$(PlatformName)\Release\$(PlatformToolset)\dynamic\`

Regards
P

PS : Why all VS201x use the file libzmq.import.props in VS2015 path ?

**Comment by bluca** [comment]
@bbdb68 @evoskuil any suggestion?

**Comment by dcube9** [comment]
1° Fix file libzmq.import.props in Master
2° Move file *.props from VS2015 in a common path (like generic props in `....\builds\msvc\properties`)

Dont you ?

**Comment by evoskuil** [comment]
Originally the import props were pulled from each build independently. There was a PR a while back that changes that behavior in order to reduce duplication. I have in the past managed the duplication using local scripts that emit the various VS platform versions by making small modifications to one of them that is used as a master. In one of my more recent updates I accommodated the change that centralized the properties files. It's not my preferred approach as I like the VS versions to be independent (once generated).

One option would be to revert that change, otherwise there needs to be a correction to link properly to the master (VS2015) repo from the others. I'm a little confused though because I thought I did that (the latter) already.

**Comment by bbdb68** [comment]
For a newcomer, having both a CMakeLists and solutions is confusing IMHO... why are both maintained ?

**Comment by evoskuil** [comment]
I personally don't know anything about cmake. The VS projects have been around for a long time. I started maintaining them along with a bunch of others and developed the techniques in place in order to make them manageable. and reliable.

**Comment by bluca** [comment]
Those using cmake for their project need cmake here as well, and it's not only for windows but for other OSes as well

**Comment by evoskuil** [comment]
Sure, I'm just not aware of the advantages of the VS projects over those generated by cmake.

**Comment by bbdb68** [comment]
cmake generates the visual studio .sln files, so cmake generated files can be used for IDE operation, not only msbuild.

IMHO There is no best solution, as long as provided solution works smoothly. It is probably just a matter of documentation so that newcomers easily know the right/officicial  way to compile ZeroMQ on their systems. 

And many windows uses would just be happy with binary downloads, but I understand that operation of web sites is not completely setup theses days and that it will take some time.

Sorry this not directly related with the issue.

**Comment by dcube9** [comment]
Ok, thank for replies.
1st I'm a newbe
I did not know that "props" files are generated from CMAKE.
At this point I suppose that the problem is in CMAKE or in the "source" files that CMAKE processes.
I manually revise the "libzmq.import.props" file as mentioned in the original post.

**Comment by evoskuil** [comment]
I have to assume that the cmake generated projects and solution aren't optimal for user interface, managing the multiple "standard" build configurations, or providing imports for dependent projects.

**Comment by dcube9** [comment]
I dont know well cmake, I have found it in some other open source projects.
I think it works well, after fixed the paths the build run well till the end.
The use of props file it's very clever.

**Comment by zstang** [comment]
in this file "builds/msvc/vs2015/libzmq.import.props" a absolute directory name of zeromq root path is assumed as "zeromq"; make sure the root path name is just zeromq solve this problem,   or remove  subpath "..\libzmq" from "AdditionalLibraryDirectories" and "Copy" in  builds/msvc/vs2015/libzmq.import.props;

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2347

**Comment by mlodew** [comment]
Fix #2347 leads to problems when building czmq on windows using the build.bat files in the visual studio project folders. The bat files copy the file libzmq.import.props from libzmq to the respective folder in the czmq build directories. Changing the path 
`$(ProjectDir)..\..\..\..\..\libzmq\bin\ `
to 
`$(ProjectDir)..\..\..\..\bin\`
will prevent the czmq build from finding libzmq.lib. 
This issue (#2341) should not arise, when the project folder is named 'libzmq'. Maybe this could be made clear better in the documentation.

**Comment by bluca** [comment]
Could you please send a PR to fix both?
