### ISSUE TITLE
tests don't test in release mode

### ISSUE THREAD

**Issue by fhriley** [zeromq/libzmq#2571]
Tests do their check for success by using assert(). For example, every check in test_udp is done using assert(). When building release with CMake, -DNDEBUG is added to the cflags. NDEBUG turns off assert(), which means the tests won't actually do their checks in a release build.

**Comment by bluca** [comment]
Is it possible to change CMake to stop it defining NDEBUG? If so, could you please send a PR to do it?

**Comment by sigiesec** [comment]
This only applies to building the tests, however. NDEBUG should not be defined when building the library as release. 
However, in the longer term, the tests should probably make use of a proper test framework such as https://github.com/libcheck/check (C) or https://github.com/google/googletest (C++)

**Comment by bluca** [comment]
The problem is that we need to support very old platforms like Solaris or AIX or Windows XP where these might not be available or work - being able to build and run without any external build dependency apart from libc++ is very important I think.
In my experience, test frameworks become very useful once advanced features like mocking are needed, but by avoiding hard dependencies we can dodge the need for it.
Is there any specific feature you have in mind that we lack now?

**Comment by sigiesec** [comment]
@bluca I am not sure which platforms are supported by the mentioned test frameworks, this must of course match. Dependencies should not be arbitrarily added, but I think a test framework is something that is quite necessary.

What I particularly dislike about the current tests are two points
# test cases cannot be run in isolation, I can only run one test executable with all its tests. if one crashes (and due to the use of cassert, they crash in case of any failure), I cannot tell if the remaining test cases within that executable run fine. (converting each test case into an executable of its own would solve tht problem, but I do not consider that approach to be maintainable, in particular when you want to write parametrized test cases). 
# assertions cannot be formulated in a sophisticated manner, and the result of them is not "rich". a test framework allows me to say something like ASSERT_EQ( 1, count ) and if it fails it outputs the actual value of count
# the result is not easily processable. I do not get a report file, which says which tests have been successful and which not. 

While it is not currently measured AFAIK, I suspect that the code coverage of the existing tests is not too good.

Mocking is not really a feature of a unit test framework IMO, but somewhat separate from that (I know that googletest and gmock have grown together, but do not think this is a particularly good idea).

**Comment by sigiesec** [comment]
Two more problems without a test framework: 
* Where there are multiple test cases per test executable, you cannot easily see which test case failed, unless you add custom output, which additionally impairs code readability/maintainability.
* It is cumbersome to write multiple test cases with common setup/teardown code.

**Comment by sigiesec** [comment]
@bluca I think I will try to integrate http://www.throwtheswitch.org/unity and implement some tests with that. It is a single C file (plus header), so we can just commit it into the libzmq repo like we do with tweetnacl. So no build dependency is added.

**Comment by sigiesec** [comment]
I did a prototype using unity for test_socket_null, in 

The output now looks like this, if some assertion is violated:
```
D:\Dev\libzmq\tests\test_socket_null.cpp:40:test_zmq_socket_null_context:FAIL: Expected 22 Was 14
D:\Dev\libzmq\tests\test_socket_null.cpp:124:test_zmq_close_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:125:test_zmq_setsockopt_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:126:test_zmq_getsockopt_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:127:test_zmq_socket_monitor_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:128:test_zmq_bind_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:129:test_zmq_connect_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:130:test_zmq_unbind_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:131:test_zmq_disconnect_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:134:test_zmq_join_null_socket:PASS
D:\Dev\libzmq\tests\test_socket_null.cpp:135:test_zmq_leave_null_socket:PASS

-----------------------
11 Tests 1 Failures 0 Ignored
FAIL
```

Note I changed the assertion to assert something that is not the case:
```
void test_zmq_socket_null_context ()
{
    void *s = zmq_socket (NULL, ZMQ_PAIR);
    TEST_ASSERT_NULL (s);
    TEST_ASSERT_EQUAL_INT (EINVAL, errno); // this is line 40 as indicated above, actually enum is set to EFAULT in this case
}
```

This automatically outputs the actual value, and continues to run the remaining tests as you can see above. It doesn't support running each test case in a subprocess though, so execution could continue on a crash (e.g. an zmq_assert failure within libzmq), other more complex test frameworks would be able to do that.

**Comment by sigiesec** [comment]
@bluca unity is under an MIT license.

**Comment by bluca** [comment]
Ok, great! MIT is compatible with LGPL3 so we are fine.
But we need to include the license text as the sources don't include it, so please also add license.txt from https://github.com/ThrowTheSwitch/Unity/blob/master/docs/license.txt in external/unity.
Also perhaps a version.txt file, with the unity tag and a link to the github repository, so that it's documented which version it is and where it comes from.

**Comment by sigiesec** [comment]
@bluca Ok, sure, I added the files.

**Comment by sigiesec** [comment]
This can be considered fixed now, I just reopened to remove the stale label.
