### ISSUE TITLE
Curve Server : Assertion failure during processing of INITIATE command

### ISSUE THREAD

**Issue by kumarsm** [zeromq/libzmq#2608]
https://github.com/zeromq/czmq/issues/1470

The issue was reported against czmq, should have been posted here.

**Comment by evoskuil** [comment]
I assume this is a regression resulting from recent changes to ZAP connection.

**Comment by bluca** [comment]
The original report is a year old, so it's unlikely - seems to be a very specific corner case with server doing the connect and abruptly interrupting and restarting, and the client doing the bind.

**Comment by kumarsm** [comment]
Correct, it is not a regression.  I have seen this since 4.1.4.   By running gdb over server connect and server bind scenarios, I figured out that

zmq::session_base_t::pipe_terminated() is not called in server connect scenario when client restarts (disconnects).  I am not conversant with the

code enough to figure out where in the code this function should be called when client disconnects.


________________________________

**Comment by bluca** [comment]
@evoskuil @somdoron I think the issue here is that when the CURVE server connects, the session_base is always the same. So zap_connect asserts because zap_pipe is already configured:

https://github.com/zeromq/libzmq/blob/master/src/session_base.cpp#L326

Changing that assert to ```if (zap_pipe != NULL) return 0;``` fixes this immediate problem.

Is it the right thing to do, in general?

I think it makes sense, as the session is the same one, and there's no reason to tear down and set up again the zap connection.

Am I missing something?

**Comment by bluca** [comment]
And just to check, if the client restarts (and re-binds) with a different client cert that is not configured in the connecting server, it is correctly refused.

**Comment by somdoron** [comment]
Make sense to me.

**Comment by evoskuil** [comment]
@bluca Sorry for not being much help on this. Just got back from 3 weeks on the road with only my phone.

**Comment by bluca** [comment]
No worries! When you have time, let me know if you spot something I missed
