### ISSUE TITLE
when sending TERMINATE to zmq_proxy_steerable(), EAGAIN is returned

### ISSUE THREAD

**Issue by f18m** [zeromq/libzmq#2616]
I added a ZMQ proxy thread to my application.
Such proxy has frontend and control socket transport of type 'inproc',
backend socket transport is 'tcp' . The proxy runs in its own thread
and collects messages coming from other threads that have PUB sockets
and 'inproc' transports (connected to the proxy frontend).

For the control socket I do the following: create a SUB socket (with
inproc transport) and provide it to zmq_proxy_steerable(); then I
create a PUB socket (same endpoint).

At the shutdown of my application I send "TERMINATE" over the control
PUB socket:

// ask the proxy to terminate:
int rc = zmq_send (m_control_pub, "TERMINATE", 9, 0);

// IMPORTANT: for some reason with libzmq 4.2.2 I always get errno==11
even if I'm not using ZMQ_DONTWAIT
assert_msg( rc == 0 || errno == 11, "Failed ZMQ API with errno %d",
zmq_errno() );

As comment above says, the zmq_send() always fails with EAGAIN... is that a bug?
Note that apparently the proxy manages to exit correctly so that the
message seems to be received correctly...

I'm attaching a minimal example that reproduces the problem

**Comment by f18m** [comment]
This ZIP contains a minimal .cpp and its Makefile:

[zmq_minimal_bug.zip](https://github.com/zeromq/libzmq/files/1127947/zmq_minimal_bug.zip)

**Comment by bjovke** [comment]
@f18m According to documentation for v4.2.2, `zmq_send()` returns number of bytes sent on successful execution and -1 otherwise, see the doc: [zmq_send()](http://api.zeromq.org/4-2:zmq-send).
This was changed compared to previous ZeroMQ versions where `zmq_send()` would return 0 on success and -1 on failure.
It doesn't make sense to check errno after `zmq_send()` call since it was successful and `errno `probably kept the value from the previous function calls.

**Comment by bluca** [comment]
Yep that's the case, and note that it changed in 3.x almost 6 years ago.

Here you can find the most recent manpages:

http://api.zeromq.org/4-2:_start
