### ISSUE TITLE
[Help]: All instances of dish socket won't receive message from radio.

### ISSUE THREAD

**Issue by nayabbashasayed** [zeromq/libzmq#2801]
# Issue description:
Radio socket is sending the message "Hello World!" on 127.0.0.1. Two instances of dish sockets are running in each terminal waiting for the message on 127.0.0.1. When I send the message from radio socket, only one of dish sockets able to receive the message. Other won't.

# Environment
Ubuntu 16.04

* libzmq version (commit hash if unreleased): 4.2.1 stable
* OS: Ubuntu 16.04

# Minimal test code / Steps to reproduce the issue

1.  https://codeshare.io/5gAZJ0 For RADIO socket program
2. https://codeshare.io/GqLJdx for DISH socket program
3. gcc -Wall radio_socket.c -o radio_socket -lzmq
4. gcc -Wall dish_socket.c -o dish_socket -lzmq
5. ./radio.socket 127.0.0.1:51716 in one terminal and,
6. ./dish_socket 127.0.0.1:51716 in each of two terminals.

# What's the actual result?
Only one of the dish sockets able to receive the message.

# What's the expected result?
Both the instances are supposed to receive the message

**Comment by bluca** [comment]
Hi,

Due to how UDP works, the workflow is a little different from TCP/IPC. As you already have seen the DISH binds and the RADIO connects. If both DISH programs bind to the same address and port, the kernel will deliver the packet to only one of them.

You need to bind the 2 DISH programs to a different port each, and then connect the RADIO to both. Then you'll see that it works.

**Comment by nayabbashasayed** [comment]
Seems like we can connect 2 RADIO programs to the same endpoint. I tested it. :+1:

**Comment by bluca** [comment]
Great, thanks for confirming!
