### ISSUE TITLE
Problem with PUB/SUB sockets

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/libzmq#2826]
# Issue description
I have simple publisher and subscriber samples:
**Publisher**: It is publishing 15 events at the interval of 2 seconds.
**Subscriber**: It is subscribed for the events.

But on subscriber only 14 events are coming.

# Environment

* libzmq version: 4.2.2
* OS: Linux 

# Minimal test code / Steps to reproduce the issue
1. Run the subscriber sample , it will subscribed for events.
2. Run the publisher it will send the 15 events at the interval of 2 seconds.

But subscriber is receiving only 14 events. Event is dropped. 
From publisher it is showing all the 15 events are published. But subscriber is receiving only 14.
Is it publisher or subscriber problem.  

# What's the actual result? (include assertion message & call stack if applicable)
 subscriber is receiving only 14 events.

# What's the expected result?
 subscriber should receive all the 15 events.

**Comment by jay11ca39** [comment]
@bluca , 
As per my understanding, first message is being ignore might be as connection is in progress. Is any thing I missed out?

**Comment by bluca** [comment]
Yes the pub/sub pattern is "lossy" by design - it will not wait for subscribers. So you most likely have a synchronisation problem: by the time the subscription message has been processed by the publisher, the first message is already gone.

If you need to synchronise, then you'll have to do it in your protocol. But then pub/sub might not be the best choice - that pattern works best when the individual subscribers can be resilient to message losses and can recover. A common pattern is to have a monotonically increasing unique message id, and an out-of-band reliable channel where slow subscribers can request a retransmit separately.

**Comment by jay11ca39** [comment]
Thanks @bluca for your explanation , I got your point. It takes some time from subscriber to connect so, it missed the first packet during that time.
