### ISSUE TITLE
Static linking rationale on windows/msvc

### ISSUE THREAD

**Issue by cowo78** [zeromq/libzmq#2873]
# Issue description

Building a static library on windows/msvc using the supplied solution for msvc2015 sets the runtime library to "Multi-threaded (/MT)" which stands for "static library" in msvc terminology. As far as I understand the whole thing this means that the libzmq static build brings in the static C library, and I think this is seldom the intended behaviour from a library user perspective.
So I would like to ask what is the rationale behind the choice and would suggest to switch to "Multi-threaded DLL" linkage in windows/msvc builds. 

# Environment

* 4.2.3
* OS: windows
* Compiler: msvc2015

**Comment by evoskuil** [comment]
It is necessary to prevent runtime failures.

**Comment by sigiesec** [comment]
What runtime failures? I have not seen such, and we are using the dynamic runtime libraries with a static libzmq as well.

We build most external libraries (boost, libzmq, ...) as static libraries, and link them into coarse-grained DLLs. Within one the link scope (EXE, DLL), the same runtime variant must be used by all objects/libs linked together. However, we use the Multi-threaded DLL runtime everywhere, and also change the libzmq defaults for our build as suggested by @cowo78. 

Overall, I think there are use cases for both /MT and /MTd. This choice cannot be made for every user of a library. It depends on the usage context. 

For example, boost supports both variants, via the --runtime-link option. I think the default there is shared, for both static and dynamic builds of the boost libraries.

**Comment by cowo78** [comment]
@evoskuil can you elaborate? What runtime failures?

Of course there can be use cases for MT and MD both. There can be multiple targets for static lib + <static|dynamic> libc.

Since there's nothing like that today I was wondering about the rationale.

**Comment by evoskuil** [comment]
This is a pereniel question here and elsewhere and well [documented by Microsoft](https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx). There is a good description of the issue (and others) [here](http://siomsystems.com/mixing-visual-studio-versions/). Note the comment on static linking CRT in the case where a DLL dependency has linked it dynamically.

The only rational way for a library to link the runtime is consistently with the build type. Dynamic for dynamic build and static for static build; debug for debug build and non-debug for release build. The library does not offer a differentiated single vs. multiple threaded build, so all builds are linked as multithreaded. If you link to another lib that uses the sungle threaded runtime it is a failure scenario.

The boost runtime linkage should be matched accordingly. See most popular answer [here](https://stackoverflow.com/questions/9527713/mixing-a-dll-boost-library-with-a-static-runtime-is-a-really-bad-idea). Defaults are defaults, not always correct.

**Comment by sigiesec** [comment]
@evoskuil I have not found anything in the links you shared that backs your claim. We are talking about the runtime to use when libzmq is built as a static library. The last link discusses if it is a good idea to use the static runtime in a dynamic library (in that case boost), and I agree that it is not a good idea. 
And since this applies to any dynamic library, for some static library it depends on how it is used. If it is used to link into an executable, you could use either the static or dynamic runtime, as long as you do this consistently. In fact, mixing runtimes would lead to linker errors in that case.
However if you intend to link the static libzmq into a dynamic library (which we do), you should use the dynamic runtime as argued in the boost link, and in the Microsoft link:
Because a DLL built by linking to a static CRT will have its own CRT state, it is not recommended to link statically to the CRT in a DLL unless the consequences of this are specifically desired and understood.

**Comment by sigiesec** [comment]
I think it is possible under some circumstances for a static library to not be bound to the static or dynamic runtime at all, but defer this to the time of linking.

**Comment by evoskuil** [comment]
If you build as a static lib and link the runtime dynamically, and link in another static lib that has linked the runtime statically, you have a failure condition. It is of course *possible* to have consistently mismatched linkage, but it requires coordination across all libraries.

Deferring (and then safely coordinating) linkage is fine unless you are not building every dependency. This condition may result from mismatching links to other Windows libs that link the CRT as well.

**Comment by cowo78** [comment]
Well, the siomsystems page was a really nice sum up of the issues, that are old and crusty indeed.
IMHO if you don't have 3rd party closed dependencies everything can be linked to the same dynamic libc and since we're not talking about embedded systems the static link option is not of much interest.
I would appreciate the option to build the library in every combination (DLL/static + dynamic/static libc) and leave the choice up to the user. I can contribute this stuff for msvc2015 platform.
I am not thinking about changing the default binary distributions or introducing elaborate naming schema like the boost one.

**Comment by evoskuil** [comment]
It seems extremely likely that Windows libraries that depend upon CRT are being linked by ZeroMQ (and/or could be at any point in the future). In this case providing this option creates undefined behavior, as well as material additional complexity in the build system.

**Comment by evoskuil** [comment]
Bottom line, shared state is pure evil. The CRT shared state fragility is very difficult to detect and is managed by convention. Deviating from those conventions is likely to produce insidious failures.

I would recommend considering your requirements. IMO this rationale doesn't hold up:

> this means that the libzmq static build brings in the static C library, and I think this is seldom the intended behaviour from a library user perspective.

* Function-level linking ensures that only the linked functions are loaded into your static library.
* The common intended behavior for static linking is to incorporate dependencies to the extent possible,
 maximizing portability and reliability.
* The common intended behavior for dynamic linking is to share dependencies to the extent possible, minimizing size and facilitating dependency updates.
* Dynamic linkage for static libs is generally limited to core/universal operating system components.
* The CRT is compiler-specific, making the a DLL-link dependent on a redist, which can be a problem.

**Comment by cowo78** [comment]
Well, advapi depends on msvcrt, for example, and since I don't know what kind of CRT the system libraries are using I must assume they're doing a good job in not messing up with malloc/free boundaries.
I see your points, and of course I agree, but I don't see how they contradict my statement. At any rate, let's say that I want to have the choice of choosing between static/dynamic CRT because I have a dependency that does not cope well with static CRT (i.e. QT) and I am of course prepared to walk the vcredist way; what is wrong with that?

**Comment by evoskuil** [comment]
> I have a dependency that does not cope well with static CRT (i.e. QT) and I am of course prepared to walk the vcredist way; what is wrong with that?

It implies that you should be building a DLL vs. a static lib, though I understand you might not want to ship multiple DLLs (i.e. including ZeroMQ).

This is a (former) Qt limitation, as its libraries dynamically link the CRT even when built statically, which causes the above-described [failures](https://stackoverflow.com/a/4804977/1172329) when another library statically-links it. From the text:

> we have experienced memory problems

it is clear that Qt did not understand this issue initially and attempted to get away with always dynamically linking despite enabling a static build. The result was just the type of problem we are mitigating by ensuring that the build is always aligned. They have since sort-of [patched this issue in 5.5](https://stackoverflow.com/a/32613840/1172329) by allowing the developer to explicitly link CRT statically. It is still necessary however to ensure that all dependencies do the same. My recommendation is to use the Qt `-static-runtime` option when building a static library.

**Comment by sigiesec** [comment]
@evoskuil You are discussing recommendations for how to organize linking in general. This has consequences for any library, not (only) specifically for ZeroMQ. However, if someone does not follow your recommendations, it may make sense or be required to build a static libzmq using a dynamic runtime. Even if these circumstances were quite special, it would be desirable if we supported it without additional hassles.

I think you make some implicit assumptions that do not apply universally. I also think that your phrase "align linkage" is misleading. Maybe we can discuss this further in another forum.

**Comment by evoskuil** [comment]
Visual Studio build configurations are nothing more than arbitrary sets of configuration options. There are unlimited possibilities. The set of build configuration that wee have preconfigured are not intended to satisfy every possible scenario. They should instead be considered maintainable best practices. There is no equivalent in autotools for example. One can change any configuration property via the build command line. Supporting every possible variation in the precinfigurations is not maintainable. These default properties have worked out very well for several years in libzmq, libsodium, libbitcoin and a number of other libraries.

**Comment by mxgrey** [comment]
> it is clear that Qt did not understand this issue initially and attempted to get away with always dynamically linking despite enabling a static build.

I don't think that's an accurate evaluation. Qt understood exactly what it was doing. The choice of the dynamic run time was to support dynamically loaded plugins without putting heavy restrictions on what kind of APIs those plugins can offer. If you use a static run time for your plugin library, then the API of your plugin would have to avoid using the STL (almost) entirely, and it would have to provide custom allocation+deallocation functions for every type that you want to pass across shared library boundaries.

Note that when you compile Qt using the `-static-runtime` option, you effectively disable any ability to use plugins in your Qt application or library. That's an enormous feature loss, but it may be palatable for people who are absolutely certain that they will never want their application to support plugins and instead prefer the portability that static libraries offer.

As a developer whose current focus is plugin-based frameworks, I think it would be valuable to at least recognize that there are cases where you want to link to a static version of ZeroMQ while having it use the dynamic run time. For example, I may want to statically compile ZeroMQ into the DLL of my plugin library to make that plugin DLL easier to port around. I still need ZeroMQ to use the dynamic run time, even though it's a static library.

Luckily I choose to exclusively use cmake, and cmake configures the build to use the dynamic run time by default, so this is a non-issue for me personally.

**Comment by evoskuil** [comment]
If Qt understood this issue initially they would not have proposed changing linkage as a solution to their “memory problems”. But guessing their motivation isn’t necessary in understanding that those problems exist. If you build a static lib with dynamic runtime or dynamic lib with static runtime you are very likely to encounter linkage with another lib that has a conflicting runtime linkage, with the corresponding insidious failures.

As I pointed out previously, these default configurations are just that. It doesn’t fail to recognize that people might accept this risk, or prevent them from doing so, it just doesn’t give them a foot gun.

The scenario you are describing, static linkage if zmq into an dynamic lib, with dynamic linkage of the crt is safe, because ultimately you have a dynamic lib linking the crt dynamically. On the other hand, the presumably far more common scenario of zmq statically linked into an executable while dynamically linking the crt is a recipie for failure, since all other crt linkage (by other static libs and the executable) is likely to by static.

So in the exceptional case where somebody actually understands these issues and has a scenario that benefits from deviation from the default standard configurations (like your preference for avoidance of shipping a zmq dll when shipping a dll plugin) it seems perfectly reasonable to expect that person to override a default configuration property using a build configuration option.

**Comment by mxgrey** [comment]
It's not much of a guess. Using the static runtime anywhere in a plugin framework kills the possibility of using runtime-loaded plugin libraries (unless you want to be constrained by the limitations I mentioned earlier) full-stop. That's most likely the "memory problems" they were referring to. Qt has always been a plugin-based framework, so it's not surprising that they initially tried to impose the requirement that all Qt libraries and Qt-consumer libraries (be they static or dynamic) use the dynamic runtime. I imagine they decided to start supporting the static runtime because there were enough consumers who wanted to be able to move around a single executable file and who didn't care about loading plugins at runtime.

Your point is definitely fair, that the far more common use case of a statically linked library is to be combined into a single application that will be linked with other statically linked libraries, all of which are likely to be using the static runtime.

I genuinely have no idea how difficult this setting is to modify in a Visual Studio project, since I avoid manually configuring Visual Studio projects at all costs (as mentioned earlier, I use cmake for that), so I can accept that it's probably something that a knowledgeable developer would/should know how to do easily enough.

It may be worth noting that the default setting for cmake (including the current libzmq cmake script) is to use the dynamic run time, even for static libraries. That may become an increasingly popular choice as cmake becomes more widely used on Windows and as Unix developers start supporting Windows in their projects, so this issue may start to come up more regularly. You might want to brace yourself for that :wink:

**Comment by evoskuil** [comment]
Changing any configuration property can be accomplished at the msbud command line. I don’t do it much, but there is an issue in this list so where that describes it in detail. Of course the same can be accomplished by simply changing the CRT linkage setting in the VS GUI. The only downside to that is that it commits the change to the source-controlled project file.

It doesn’t surprise me that cmake would default to a configuration that is unsafe in the primary use case :).

**Comment by cowo78** [comment]
Just trying to sum up things.
I think that this issue brings valuable information along if anyone cares to dig, but as far as I understand there's value in providing an option for both static and dynamic CRT.
Probably the shortest path would be to modify the official .bat scripts and dig into msbuild, something I can do and test on msvc2015.
Thoughts?

**Comment by evoskuil** [comment]
I feel there was agreement that (1) the only valid scenario was extremely limited and advanced, (2) the preconfigured builds in the GUI cannot include a cross product of all options, (3) the CRT linking option is in fact available in the GUI, and (4) the option can be controlled via the build command line. If any of these points are still unclear we should clarify them. Based on this understanding I personally cannot see attempting to build this sort of couplexity and end-user risk into the preconfigured set of builds.

**Comment by sigiesec** [comment]
I don't think that there is agreement on (1). I disagree, and as I understood the discussion, some others participants also disagree.
