### ISSUE TITLE
Use TCP loopback fastpath in zmq::signaler_t::make_fdpair if available

### ISSUE THREAD

**Issue by sigiesec** [zeromq/libzmq#2899]
From Windows 8 / Server 2012, a new socket option is available that improves performance of TCP loopback connections, which could improve performance of zmq::signaler_t.

For more information, see https://blogs.technet.microsoft.com/wincat/2012/12/05/fast-tcp-loopback-performance-and-low-latency-with-windows-server-2012-tcp-loopback-fast-path/

**Comment by sigiesec** [comment]
@thalman @karolhrdina This is what I was talking about which should be very easy to implement.

**Comment by kachanovskiy** [comment]
this one breaks the build in VS2010, for example, despite I am on Windows 10 where this one is supported. The reason, I think, is that Windows SDK bundled with VS2010 is too old to know about this option, and newer SDKs won't be detected by VS2010 (it could be still possible to make use of new files,  but certainly would require some effort).

The error happens in src/tcp.cpp line 342 due to SIO_LOOPBACK_FAST_PATH not defined.

If this change is only about passing this particular option, the workaround is to enclose it into "#if defined SIO_LOOPBACK_FAST_PATH" guard macro, because this is defined with newer SDKs from past-VS2010 versions.
Where it happens (zmq::tcp_tune_loopback_fast_path) is probably THE place to surround by such a guard.

an (maybe better) alternative is to enclose it into VS version checking macro to hide it from VS2010, for example, and if someone with, say, VS2012 also hits this - we could raise the bar again.

Will you have a look at this, or should I create a pull request?

**Comment by bluca** [comment]
Please send a PR

**Comment by kachanovskiy** [comment]
#2945 fixes this for me (VS2010).

**Comment by bluca** [comment]
Thanks!
