### ISSUE TITLE
use of tweetnacl is considerably slower than libsodium

### ISSUE THREAD

**Issue by chrisjbillington** [zeromq/libzmq#3006]
Tweetnacl seems to result in [considerably slower encryption than libsodium](https://github.com/zeromq/pyzmq/issues/1148) (about a factor of 10 - see linked issue for an example with pyzmq). I've been prodding packagers to try and get libsodium linked as required in packages when used by pyzmq, but for both the pip wheels and [Anaconda package](https://github.com/ContinuumIO/anaconda-issues/issues/8932) this looks unlikely to happen on Windows, and I'm close to giving up on being able to get fast crypto for my Windows users.

One hope I have is that it's possible that tweetnacl might not be fundamentally slow, and that there might be something about the way zeromq uses it that makes things slow. Pieter said [here](http://grokbase.com/t/zeromq/zeromq-dev/162aa70zpr/defaulting-to-tweetnacl) that the change to tweetnacl would not change anything significant in terms of performance, but that appears not to be true, uness I'm missing something. It would be great if tweetnacl could be almost as fast as libsodium, as it's certainly easier for the packagers.

I've only been able to test that tweetnacl is slow with zeromq 4.1.6, as that is the version bundled with pyzmq, and I haven't managed to build pyzmq against other versions myself (or to make a test case in C/C++).

**Comment by sigiesec** [comment]
This mainly addresses tweetnacl rather than libzmq. Libzmq merely packages tweetnacl. Apart from that, tweetnacl is inherently slower than libsodium. Tweetnacl is small and portable, while libsodium contains many optimizations for different platforms.

I am not sure, but doesn't pyzmq use a dynamic build of libzmq, i.e. a DLL? Then you can exchange the packaged DLL by another built against libsodium.

**Comment by evoskuil** [comment]
The Visual Studio builds include the option to link libsodium.

**Comment by bluca** [comment]
Nobody should use tweetnacl in production. Speed is the last of its problems. It has not been audited, it's never updated. Libsodium on the other hand it's maintained, audited, gets security updates and is highly optimised with hardware acceleration support. Tell the packagers to switch to libsodium ASAP before they end up with a security nightmare on their hands.

I'm beginning to think it was not a good idea to embed tweetnacl...

Anyway, we are definitely not going to mess with that code, there is no D.J. Berstein-level of cryptographer among us afaik so it would be a disaster.

**Comment by chrisjbillington** [comment]
I can do whatever I can with my own packages, but my users are going to be installing pyzmq via either conda or pip, and it's not really within my ability to build and maintain binary packages for all platforms to ensure all my users have good crypto. I was not aware that tweetnacl was not considered production worthy (other than the speed thing), and would agree that something not production-worthy probably shouldn't be included by default.

It seems from the outside like a constant battle for the package maintainers to be able to build everything on Windows. Anaconda [won't build pyzmq](https://github.com/ContinuumIO/anaconda-issues/issues/8932) linked with anaconda's zeromq—built with libsodium—because completely unrelated R packages in the same package manager need zeromq to be built with gcc, which is presumably not ok with pyzmq, I'm not sure why, and pyzmq *used* to bundle libsodium (not sure if it built on Windows), but they stopped doing so, because ["libsodium has build troubles on Windows"](https://github.com/zeromq/pyzmq/commit/9e23a6a1cde2c54598b9fc5976232b688410ce9c), so I can see why tweetnacl was an attractive alternative.

I'll keep prodding package maintainers for now...

**Comment by bluca** [comment]
Sorry for the hassle. But as I said we don't have cryptographers working with us so we have to thread extremely carefully around that piece of code.

The production problem is that it's not audited and there's no maintenance support for it, unlike for libsodium, so it's extremely risky to blindly trust its crypto primitives.

If that can help, libzmq and pyzmq are built with GCC on all Linux distros - so not sure what the issue is there, but quite sure it's not to do with us.

**Comment by bluca** [comment]
That sounds quite complicated -  I would suggest to just focus on getting that Windows binary rebuilt with libsodium. It's supported and it works out of the box - not sure why that Windows package system doesn't use it. Drop them and find an alternative maybe?

**Comment by mingwandroid** [comment]
> It's supported and it works out of the box

> Drop them and find an alternative maybe?

@bluca, for the record, the history here is that `zeromq` has been in a very state (unusable due to race conditions) on Windows since at least last September when I first tried to use it with `pyzmq` and for that reason I was forced to not use it with, and not using it means not using libsodium, obviously.

It's only now that 4.2.4 has been released that it works again thanks to the [efforts](https://github.com/ContinuumIO/anaconda-issues/issues/8932#issuecomment-374649732) of @sigiesec
