### ISSUE TITLE
How to build libzmq for WIndows using MinGW

### ISSUE THREAD

**Issue by arunpkqt** [zeromq/libzmq#3199]
# Issue description
It is not clear from the documentation or GitHub page on how to build czmq on windows using MinGW. Can someone explain it or point to documentation which explains the steps to build on Windows?

**Comment by zedalaye** [comment]
I experienced the same adventure some days ago :) libzmq was not a problem, czmq and zyre involved a lot more work.

* I choose to build it using Visual Studio 2017 (Community Edition is fine)
* Visual Studio 2017 now supports cmake, so, instead of opening the "SLN File" (from builds\msvc), just open the WHOLE libzmq directory, CMakeFile is automagically detected and Visual Studio prepares everything in background.
* Next choose "x86-Release" (if you want 32 bits librairies) or "x64-Release" (if you want 64 bit libaraies) from the combobox (the cmake process is relaunched in background)
* You will see something like `-- Build files have been written to: C:/Users/Pierre/CMakeBuilds/01e9cd7b-24f9-bb38-bb3e-6cbd75d8c82b/build/x86-Release`, that means that binaries will be build at that place...
* Finally choose "CMake (Menu") / Generate only / libzmq-mt-4_2_5.dll (bin\libzmq-mt-4_2_5.dll) 
* Wait and see :)

Note that the SLN Files (as well as MingW Makefiles) can also be auto-generated by zproject and GSL, so by building first GSL and zproject in a Linux Box (yeah !) you can re-generate a lot of things in zmq-related projects (like czmq, zyre and malamut)

* Git clone everything (gsl, zproject, libsodium, libzmq, czmq, zyre, ...) in a directory that is shared between linux and windows (I have not tried to use ubuntu bash for windows to do that)
* Build gsl (see readme), AND INSTALL IT (sudo make install)
* Build zproject (see readme) AND INSTALL IT (sudo make install)
* In every zmq-related project you will see a "project.xml" file, within your Linux box, just run "gsl project.xml" to rebuild all makefiles and related goodies for this project.

Then in your windows box :
* Build libzmq using process described above
* For every libzmq dependent project run configure.bat (from build\msvc) and open the build\msvc\vs2017\<project>.sln file to build the project.

Hope this help.

**Comment by arunpkqt** [comment]
@zedalaye Thanks a lot for the info. Will try to follow the same.
A quick question,
have you used the DLL with any Qt-based project? Our application is based on Qt and uses QMake and MinGW compiler on Windows.

**Comment by zedalaye** [comment]
No. I'm in process to integrate czmq and zyre in a Delphi (VCL) application.

**Comment by sigiesec** [comment]
This is the libzmq issue tracker, but you are referring to https://github.com/zeromq/czmq
