### ISSUE TITLE
New socket option ZMQ_ROUTER_NOTIFY

### ISSUE THREAD

**Issue by hoditohod** [zeromq/libzmq#3201]
**This issue is more of a debate than a concrete issue**

ZeroMQ's socket abstraction is really powerful that it handles multiple connections in the background and the library goes far to hide the complexity of managing these connections. This is beneficial as it simplifies application code. Usually knowing that messages are round-robin out and fair-queued in is enough. And where it is not: the ROUTER socket is used which identifies its peers by routing-id and allows targeted responses.

Though the routing-id's are exposed to the application by the socket, much of the connection management still remains hidden. This is in accordance with other zmq socket types, but I think it imposes limitations on the user code. 

The specific case I would like to discuss is: when a peer disconnects from the ROUTER. Most ROUTER based applications maintain state related to the routing-id (at least they store the id itself), and need to know when the state can be released. There are ways to achieve this (MANDATORY routing, heartbeats, timeouts, get_peer_state), but none of these give the "if libzmq releases the routing-id, then let me know".

This topic comes up from time to time on the mailing list and the github issues, and there are still uses-cases not covered by the above listed solutions, so it's worth revisiting.

**Proposal**

What I propose is a ZMQ_ROUTER_NOTIFY socket option that (as the STREAM counterpart) sends a routing-id only message when the connection is established or closed. 

I'm completely unfamiliar with libzmq internals (though I'm a user for years), I would do the PR, but I need expert guidance. The first question before I start to dig myself into the code: is it feasible at all, or there're some design obstacles that are very hard to overcome?

What do you think?

**Comment by bluca** [comment]
There is already machinery for this with mandatory routing - and I'm not convinced this would be a good addition. There's a reason these details are hidden - it's because they get abused. From day one zeromq abstracted away the low level details, to encourage better designed application protocols for distributed systems, as explained with examples in the zguide.
If one really wants to micro-manage all the TCP connections, then the system socket APIs can simply be used.

Having said that, in compliance with C4 if you want to implement this (with tests and documentation, pretty please) nobody's going to stop you, and we'll merge it.

**Comment by bluca** [comment]
> I don't want to abuse C4, if you think this against the core principles of the library, but as I mentioned I've seen similar requests before. (Now jumping into the code to see if I can even do this or not...)

It's not an abuse - it's working as intended :-) All that is requested is that there are tests and documentation, and no backward-incompatible changes. Besides that, go for it.
