### ISSUE TITLE
PLAIN mechanism implementation not conforming to 24/ZMTP-PLAIN

### ISSUE THREAD

**Issue by huiyaozheng** [zeromq/libzmq#3500]
# Issue description

One of the the messages exchanged during the checking of PLAIN mechanism seems incorrect according to the RFC. 

# Environment

* libzmq version (commit hash if unreleased): 4.3.0
* OS: macOS 10.14.4

# Minimal test code / Steps to reproduce the issue

Use the test code at <https://github.com/zeromq/czmq/blob/master/examples/security/woodhouse.c/>

1. Start a packet capturer (e.g. WireShark) and listen on the local loopback port 9000.
2. Compile and run the example code.
3. Examine the packet trace and locate the first message sent by the client after the greeting.

# What's the actual result? (include assertion message & call stack if applicable)

The client sends "\x04\x15\x05WELCOME\x05admin\x06secret"

# What's the expected result?

The client should have sent "\x04\x15\x05HELLO\x05admin\x06secret", according to the specification in [24/ZMTP-PLAIN](https://rfc.zeromq.org/spec:24/ZMTP-PLAIN/).

**Comment by bluca** [comment]
Looks like a bug introduced by https://github.com/zeromq/libzmq/commit/7f880c256f80a60a9922d583d48d1347bb3387a5 @sigiesec do you have time to send a PR to fix it? I'm a bit swamped these days - I guess we never noticed because the server uses the same common definition now, so it was accepted, and nobody until now tried interop, and we don't have a unit test that mocks the protocol

**Comment by sigiesec** [comment]
I guess I can fix this tomorrow.

**Comment by bluca** [comment]
Thanks!
