### ISSUE TITLE
Question: ZMQ over unix domain sockets

### ISSUE THREAD

**Issue by andre-merzky** [zeromq/libzmq#3609]
I write a distributed application using ZMQ as message layer - and it works like a charm :-) - thank you! :-)

Some hosts the app needs to run on are behind firewalls, only allowing ssh access.  Some hosts are also insecure. I can tunnel a ZMQ connection via `ssh -L...` all right.  However, that opens a local port which I cannot perform any access control - any user on that (insecure) machine can access that port once the tunnel exists (I cannot use privileged ports).  `ssh -L...` allows to use UNIX domain sockets as endpoints instead though [1], and on those I *can* perform access control.

I can't figure out how to convince ZMQ to connect to that socket though - [zmq-tcp (7)](http://api.zeromq.org/4-1:zmq-tcp) explicitly documents endpoint addressed to contain port numbers.

Is there any way to connect to a UNIX domain socket when the other end is tunneled to an TCP endpoint on a remote host?

Thank you! :-)

[1] [ssh man page](https://man.openbsd.org/ssh): (emphasis mine)
```
-L [bind_address:]port:host:hostport
-L [bind_address:]port:remote_socket
-L local_socket:host:hostport
-L local_socket:remote_socket
Specifies that connections to the given TCP port *OR UNIX SOCKET* ...
```

**Comment by hoditohod** [comment]
You can bind/connect to a Unix domain socket specifying the 'ipc' protocol (ipc://&lt;path&gt;), see: [zmq_ipc](http://api.zeromq.org/4-2:zmq-ipc).

Your use-case is a bit tricky (as I understand) because one zmq end is tcp, the other is unix-domain, and an ssh tunnel sits in between. But I think it should work as the zmq wire protocol is the same for both socket types, and the ssh tunnel transmits data without modification.

**Comment by andre-merzky** [comment]
Ah, I see, thanks - I'll give that a try!  I assume that won't work for a socks5 tunnel though: my guess is that only the TCP endpoint would perform a socks negotiation?  Anyway, I'll test that, and will ping back with what I find.
