### ISSUE TITLE
zmq_ctx_shutdown has not effect before any socket is created

### ISSUE THREAD

**Issue by gummif** [zeromq/libzmq#3792]
# Issue description
Calling `zmq_ctx_shutdown` does not affect the sockets created after that call unless at least 1 socket has been created before the `zmq_ctx_shutdown` call.

This can cause threads to block forever if shutdown is called before any socket is created, but the thread creates a socket after the shutdown.

Related to https://github.com/zeromq/cppzmq/pull/377

# Environment

* libzmq version (commit hash if unreleased): 4.3.2
* OS: Linux

# Minimal test code / Steps to reproduce the issue

```c++
#include <zmq.h>
#include <cassert>

int main()
{
    void* ctx = zmq_ctx_new();
    assert(ctx);
    //void* s0 = zmq_socket(ctx, ZMQ_REP); // uncomment these for ETERM in zmq_socket below
    //zmq_close(s0);
    zmq_ctx_shutdown(ctx);

    void* s = zmq_socket(ctx, ZMQ_REP);
    if (!s)
    {
        printf("zmq_socket failed: %s\n", zmq_strerror(zmq_errno()));
        return 1;
    }
    //zmq_ctx_shutdown(ctx); // uncomment this for ETERM in zmq_bind
    int rc = zmq_bind(s, "inproc://test");
    if (rc == -1)
    {
        printf("zmq_bind failed: %s\n", zmq_strerror(zmq_errno()));
        return 1;
    }
    puts("going to block");
    char b[1];
    rc = zmq_recv(s, b, 1, 0);
}
```

# What's the actual result? (include assertion message & call stack if applicable)
`going to block`

# What's the expected result?
`zmq_socket failed: Context was terminated`

**Comment by sigiesec** [comment]
The specification of `zmq_ctx_shutdown` is not entirely clear about this, it says:
```
Context shutdown will cause any blocking operations currently in progress on sockets open within context to return immediately with an error code of ETERM. With the exception of zmq_close(), any further operations on sockets open within context shall fail with an error code of ETERM.
```
The first sentence is not relevant here, since there are no blocking operations in progress.

The second sentence refers to `sockets open within context`. It is not entirely clear if this just ought to differentiate from sockets open within a *different* context, or if this means "open at the time of the call to zmq_ctx_shutdown". We don't have any tests assertion one or the other right now. However, I think the former was meant. Allowing opening new sockets after calling `zmq_ctx_shutdown` sounds at least heavily counterintuitive. Since the context can be used from multiple threads, this interpretation (and current behaviour) is also inherently prone to race conditions, which does seem very undesirable.

I'd suggest to
* add tests that assert that attempting to open a socket after the call to `zmq_ctx_shutdown` results in ETERM
* adapt the implementation accordingly
* clarify the documentation of `zmq_ctx_shutdown` to eliminate the ambiguity

@bluca @somdoron What do you think?

**Comment by bluca** [comment]
sounds good - new sockets should definitely not be opened after shutdown
