### ISSUE TITLE
EAGAIN on sucessful zmq_recv SUB with CONFLATE

### ISSUE THREAD

**Issue by jjg-dressipi** [zeromq/libzmq#4035]
# Issue description

For a SUB socket with CONFLATE enabled, a blocking `zmq_recv` will often set errno to EAGAIN on successful (non-negative) return.

# Environment

* libzmq version  4.2.5, Ubuntu package libzmq3-dev, 4.2.5-1ubuntu0.2
* OS: Linux Mint 19.3 Tricia

# Remarks

I appreciate that this behaviour is consistent with the documentation which states that errno will be set if the return from `zmq_recv` is -1 (it does not say that errno will not be set if the return value is not -1), but it seems to violate the "principle of least surprise", is this behaviour intended?

Further, I can see that one would want to use DONTBLOCK and test errno for EAGAIN to actually implement CONFLATE; so it seems likely to me that this "leakage" of state from the details of implementation is unintentional.  If this is not the case, please close this; I just thought it worth mentioning.

**Comment by sigiesec** [comment]
I am not sure how widespread this is, and this is not the POSIX specification, but at least for Linux the manpage for errno (https://man7.org/linux/man-pages/man3/errno.3.html) specifically says:
```
a function that succeeds is allowed to change errno
```
So this behaviour is legal, and I think due to the following it is mostly unavoidable:
```
The value of errno is never set to zero by any system call or library function.
```
So, the only way this could be avoided is to save the value of `errno` at the start of `zmq_recv`. and then reset it to that value on success. But this seems too tedious to me. I think that's happening for other functions as well, which is why changing the value on success is allowed.

**Comment by jjg-dressipi** [comment]
I think "library" in this context means the C standard library (see interesting discussion [here](https://softwareengineering.stackexchange.com/questions/209729/)) but your point applies more-so to a general library; "too tedious" seems entirely reasonable, so I'll close this.
