### ISSUE TITLE
★★★An error occurs because of the Korean path.

### ISSUE THREAD

**Issue by blackCmd** [zeromq/libzmq#4201]
# Issue description
An error occurs when setting the system folder name in Korean like below.
`C:\Users\김민수`

But the error doesn't occur when setting the system folder name in English like below.
`C:\Users\James`
(Only a specific version has this error. See my test history below)

The error occurs on line 100 of `epoll.cpp`.
Please see my test code and result in the captured image below.
I think the cause of this error is a language encoding problem.
How to fix it? Plz, help me.........

Thanks! 

# My Issue Test History
4.3.5V - has error.
4.3.4V - has error.
4.3.3V - has error.
4.3.2V - has no error.
4.3.1V - not check yet.
4.3.0V - has no error.

# Environment
Windows10 20H2 + Visual Studio 2019 + Libzmq 4.3.5

# Capture images
Number 1.
![스택프레임1](https://user-images.githubusercontent.com/13531174/120130964-56fbd580-c202-11eb-90b3-e2f13355a02b.png)

Number 2.
![스택프레임2](https://user-images.githubusercontent.com/13531174/120130972-595e2f80-c202-11eb-87d4-573ab5caa67c.png)

Number 3.
![image](https://user-images.githubusercontent.com/13531174/120131346-38e2a500-c203-11eb-8305-693528eb1be5.png)

**Comment by saschavv** [comment]
Hi, I have looked into this issue. I trace the problem back to the following [commit](https://github.com/zeromq/libzmq/commit/ca552d563ff358094485c9ade83159dc6922ff4f).

The crash is triggered by wide characters in the path that is created by create_ipc_wildcard_address and is 
used in the bind routine. A fix for the problem can be found in the following branch [fix_widechar_path_crash](https://github.com/saschavv/libzmq/tree/fix_widechar_path_crash).

If this issue is not picked up I will try to create a pull request.

**Comment by bluca** [comment]
please send a PR
