### ISSUE TITLE
SUB accepts multiple connects to same PUB endpoint and result is nonsensical

### ISSUE THREAD

**Issue by trevorbernard** [zeromq/libzmq#788]

**Comment by WallStProg** [comment]
I've recently run into a problem related to this one, and would like to get some feedback on a potential solution.

The problem is that for pub/sub the original fix for this issue only covers the case where the socket is a SUB socket -- PUB sockets are allowed to connect multiple times to the same endpoint, and when they do that, they receive duplicate messages.

Now, I know that there are issues related to PUB sockets connecting to SUB sockets, but in some architectures that is unavoidable, and the library/application will need to deal with those issues.

Given that, wouldn't it make sense to include PUB sockets in the `is_single_connect` test?

FWIW, that approach appears to be working in my environment, and I'm happy to submit a PR if the community is interested.

**Comment by bluca** [comment]
I think it makes sense, feel free to send a PR, thanks

**Comment by ilyakrasnovsky** [comment]
Does it also make sense to add `XSUB`  and `XPUB` sockets to the `is_single_connect` test? I've noticed the same message-duplication problem when I `connect` more than once to an existing address from an `XSUB` socket. I can open a new issue if that helps, but wanted to jump off of a relevant discussion. Thanks!

**Comment by WallStProg** [comment]
I’m not familiar with XPUB/XSUB, as I don’t use them (except w/zmq_proxy), but a couple of points:

- It would seem that hard-coding this behavior could interfere with manual handling of subscribe/unsubscribe requests — e.g. a particular application might want to use ZMQ_XPUB_VERBOSE, ZMQ_XPUB_MANUAL, etc. to handle the case of duplicate subscribe requests
- For that reason, it might be better to have this behavior controlled by a socket option?

While we’re on the topic (no pun intended), an argument can be made that silently ignoring duplicate subscription requests is not the best approach, and that it might be better to return a specific errno value (EEXIST?) in the case where a duplicate subscription is being ignored.  Of course, this would break existing code and so should also be a socket option.  Not a pain point for me, but I can imagine that it might be useful in some cases.

**Comment by ilyakrasnovsky** [comment]
I think that the `EEXIST` approach is better. I think I'd like a "`ZMQ_ERROUT_ON_MULTI_CONNECT`" socket option that only works on `ZMQ_PUB`, `ZMQ_SUB`, `ZMQ_DEALER`, `ZMQ_REQ`, `ZMQ_XSUB`, and `ZMQ_XPUB` sockets (all the ones that would otherwise be hardcoded in that `is_single_connect` `if` block). I have a workaround for my application, so no big rush, but I think I'll open a feature request for this. Thanks!
