### ISSUE TITLE
Handle leak on zmq_connect for inproc addr

### ISSUE THREAD

**Issue by dsrosario** [zeromq/libzmq#792]
This is basically the handle leak issue previously reported at https://zeromq.jira.com/browse/LIBZMQ-528. 

The following code (tested with 4.0.3) leaks 2 windows handle (sockets) per seconds.

```
#include "zmq.h"
#include "zmq_utils.h"

int main()
{
void *ctx = zmq_ctx_new();
void *server_sock = zmq_socket(ctx, ZMQ_PUSH);
zmq_bind(server_sock, "inproc://xpto");
while (1) {
    void *zsock = zmq_socket(ctx, ZMQ_PULL);
    if(zsock == NULL)
    {
    printf("zmq_socket error\n");
    exit(1);
    }
    zmq_connect(zsock, "inproc://xpto");
    zmq_close(zsock);
    zmq_sleep(1);
}
zmq_ctx_destroy(ctx);
return 0;
}
```

**Comment by bjovke** [comment]
@dsrosario @sigiesec While it doesn't make any sense to create inproc ZMQ_PUSH server socket which does nothing and create it in the same thread as it's ZMQ_PULL client, this should still not leak.
In this case probably there's no I/O thread (as already stated) to process handshake/close sequences since there's no code run for ZMQ_PUSH socket (eg. `zmq_send ()`, `zmq_close ()`...).
My question is: _Is there an existing case in the real application where both inproc sockets (server and client) are in the same thread and code of server socket is never executed? If there's really such code is there really a need for such a setup (eg. can two sockets be in different threads)?_

I'm having hard time to understand where case as this one is used and is causing leaks...

**Comment by sigiesec** [comment]
@bjovke I think the example code makes no sense as a real, *complete* use case, but it probably is a stripped-down example to demonstrate the leak.

**Comment by dsrosario** [comment]
I no longer works on the system that use zeromq, but for what I remember, the same thread can have both socket types to self notify events without messing up the order of messages at the queue, i.e., internal events or external events will be treated in order...

**Comment by bjovke** [comment]
@dsrosario Yes, you're right. There might be such a case.
But this leak can be avoided by regularly executing `ZMQ_PUSH` socket's code: `zmq_recv ()`, `zmq_send ()` and/or `zmq_close ()`.
It seems to me that the only way for this example not to leak is to execute code of `ZMQ_PUSH` socket (processing of connection termination request from `ZMQ_PULL`) either from `zmq_close ()` call for `ZMQ_PULL` or reaper thread.

**Comment by bjovke** [comment]
@sigiesec Well the first intention is thinking a way to workaround this if someone is having production code and experiencing leaks with it. I hope you agree that if workaround can be made then people will be less frustrated waiting (since 2013) for this issue to be resolved.
The second intention is just thinking out loud how it can be resolved since I'm not so much familiar with inner workings of libzmq.

**Comment by bjovke** [comment]
@sigiesec Especially when this case might require a lot of code changed.
