### ISSUE TITLE
zmq_send does not timeout when ZAP authentication fails.

### ISSUE THREAD

**Issue by hashstat** [zeromq/libzmq#882]
When a server performing ZAP authentication rejects a client with a 400 (or other non-200) error, the client, sending data with zmq_send (and presumably all send functions), reattempts the connection and authentication indefinitely, unless ZMQ_RECONNECT_IVL is set to -1. There is currently no way to limit the number of authentication failures nor is there a way for the client to tell that authentication failed (because zmq_send succeeds and performs the authentication in the background).

It seems that there are three stages to the connection: socket connection, ZMQ handshake, and ZAP handshake. A failure in any three of these should probably be considered a connection failure. Does it make sense to treat them differently? If ZMQ_IMMEDIATE is set, it seems that zmq_send (and others) should block until all three steps are performed successfully. After looking at the code, it is not immediately apparent to me how to implement any of this. Any thoughts, suggestions, etc.?

**Comment by davidblewett** [comment]
@hintjens what ticket were you referring to? #883? If so, that ticket doesn't appear to reference some kind of feedback to the client that an auth error occurred.

Currently, you can set ZMQ_RECONNECT_IVL to force the socket to not try to reconnect on authentication failure, but the client code is never made aware of any potential issues.

**Comment by hintjens** [comment]
This issue was fixed in ZeroMQ 4.1.0

**Comment by johnnykv** [comment]
@hintjens How was this fixed in 4.1.0? Was it only the reconnect strategy what was fixed, or is there also implemented visibility (logging) when auth fails (bad key, invalid key, etc)

**Comment by hintjens** [comment]
From memory, there is still debugging output whenever there's an
exceptional condition during authentication (at the libzmq side). We also
catch and deal with the timeout in libzmq, as far as I remember.
On 27 Jun 2016 10:19 pm, "Johnny Vestergaard" <notifications@github.com>
wrote:

@hintjens <https://github.com/hintjens> How was this fixed in 4.1.0? Was it
only the reconnect strategy what was fixed, or is there also implemented
visibility (logging) when auth fails (bad key, invalid key, etc)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zeromq/libzmq/issues/882#issuecomment-228862752>, or mute
the thread
<https://github.com/notifications/unsubscribe/AASzCA_SSy_gYgeRceONPCZ7QMWszndCks5qQDA9gaJpZM4BhI1G>
.

**Comment by sigiesec** [comment]
@johnnykv Monitoring events for encryption and authentication errors were recently added by #2645 and #2665 and subsequent PRs. 

Regarding the reconnect behavior: the client is sent an ERROR for ZAP 400 errors. The CURVEZMQ spec demands that the client does not reconnect in case it received an ERROR. However, the current implementation does not warrant this, to my knowledge.
